# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.chat_api import ChatApi  # noqa: E501
from swagger_client.rest import ApiException


class TestChatApi(unittest.TestCase):
    """ChatApi unit test stubs"""

    def setUp(self):
        self.api = ChatApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_chat_chat_post(self):
        """Test case for chat_chat_post

        Chat  # noqa: E501
        """
        pass

    def test_get_list_chat_list_get(self):
        """Test case for get_list_chat_list_get

        Get List  # noqa: E501
        """
        pass

    def test_load_chat_load_get(self):
        """Test case for load_chat_load_get

        Load  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
