# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hipai_client
from hipai_client.api.connection_configs_api import ConnectionConfigsApi  # noqa: E501
from hipai_client.rest import ApiException


class TestConnectionConfigsApi(unittest.TestCase):
    """ConnectionConfigsApi unit test stubs"""

    def setUp(self):
        self.api = ConnectionConfigsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_connection_config_api_connection_configs_id_delete(self):
        """Test case for delete_connection_config_api_connection_configs_id_delete

        Delete Connection Config  # noqa: E501
        """
        pass

    def test_delete_document_api_connection_configs_documents_id_delete(self):
        """Test case for delete_document_api_connection_configs_documents_id_delete

        Delete Document  # noqa: E501
        """
        pass

    def test_delete_many_connection_configs_api_connection_configs_delete_many_post(self):
        """Test case for delete_many_connection_configs_api_connection_configs_delete_many_post

        Delete Many Connection Configs  # noqa: E501
        """
        pass

    def test_document_upload_api_connection_configs_document_upload_post(self):
        """Test case for document_upload_api_connection_configs_document_upload_post

        Document Upload  # noqa: E501
        """
        pass

    def test_list_connection_configs_api_connection_configs_list_post(self):
        """Test case for list_connection_configs_api_connection_configs_list_post

        List Connection Configs  # noqa: E501
        """
        pass

    def test_list_documents_api_connection_configs_documents_id_get(self):
        """Test case for list_documents_api_connection_configs_documents_id_get

        List Documents  # noqa: E501
        """
        pass

    def test_load_connection_config_api_connection_configs_id_get(self):
        """Test case for load_connection_config_api_connection_configs_id_get

        Load Connection Config  # noqa: E501
        """
        pass

    def test_upsert_connection_config_api_connection_configs_post(self):
        """Test case for upsert_connection_config_api_connection_configs_post

        Upsert Connection Config  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
