# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hipai_client
from hipai_client.api.chat_api import ChatApi  # noqa: E501
from hipai_client.rest import ApiException


class TestChatApi(unittest.TestCase):
    """ChatApi unit test stubs"""

    def setUp(self):
        self.api = ChatApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_completions_api_chat_completions_post(self):
        """Test case for completions_api_chat_completions_post

        Completions  # noqa: E501
        """
        pass

    def test_streaming_completions_api_chat_completions_stream_post(self):
        """Test case for streaming_completions_api_chat_completions_stream_post

        Streaming Completions  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
