# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hipai_client
from hipai_client.api.company_api import CompanyApi  # noqa: E501
from hipai_client.rest import ApiException


class TestCompanyApi(unittest.TestCase):
    """CompanyApi unit test stubs"""

    def setUp(self):
        self.api = CompanyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_company_api_company_get(self):
        """Test case for get_company_api_company_get

        Get Company  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
