# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hipai_client
from hipai_client.api.users_api import UsersApi  # noqa: E501
from hipai_client.rest import ApiException


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_generate_replacement_api_key_api_users_api_keys_generate_replacement_post(self):
        """Test case for generate_replacement_api_key_api_users_api_keys_generate_replacement_post

        Generate Replacement Api Key  # noqa: E501
        """
        pass

    def test_get_api_key_api_users_api_keys_get(self):
        """Test case for get_api_key_api_users_api_keys_get

        Get Api Key  # noqa: E501
        """
        pass

    def test_get_current_user_api_users_get(self):
        """Test case for get_current_user_api_users_get

        Get Current User  # noqa: E501
        """
        pass

    def test_replace_api_key_api_users_api_keys_replace_post(self):
        """Test case for replace_api_key_api_users_api_keys_replace_post

        Replace Api Key  # noqa: E501
        """
        pass

    def test_update_current_user_api_users_post(self):
        """Test case for update_current_user_api_users_post

        Update Current User  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
