# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.model_config_api import ModelConfigApi  # noqa: E501
from swagger_client.rest import ApiException


class TestModelConfigApi(unittest.TestCase):
    """ModelConfigApi unit test stubs"""

    def setUp(self):
        self.api = ModelConfigApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_model_config_list_model_config_list_get(self):
        """Test case for model_config_list_model_config_list_get

        Model Config List  # noqa: E501
        """
        pass

    def test_model_config_upsert_model_config_post(self):
        """Test case for model_config_upsert_model_config_post

        Model Config Upsert  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
