# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.connection_config_request import ConnectionConfigRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestConnectionConfigRequest(unittest.TestCase):
    """ConnectionConfigRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConnectionConfigRequest(self):
        """Test ConnectionConfigRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.connection_config_request.ConnectionConfigRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
