# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hipai_client
from hipai_client.models.any_of_agent_config_object_direct_citations import AnyOfAgentConfigObjectDirectCitations  # noqa: E501
from hipai_client.rest import ApiException


class TestAnyOfAgentConfigObjectDirectCitations(unittest.TestCase):
    """AnyOfAgentConfigObjectDirectCitations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnyOfAgentConfigObjectDirectCitations(self):
        """Test AnyOfAgentConfigObjectDirectCitations"""
        # FIXME: construct object with mandatory attributes with example values
        # model = hipai_client.models.any_of_agent_config_object_direct_citations.AnyOfAgentConfigObjectDirectCitations()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
