# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.agents_api import AgentsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAgentsApi(unittest.TestCase):
    """AgentsApi unit test stubs"""

    def setUp(self):
        self.api = AgentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_agent_config_upsert_agents_post(self):
        """Test case for agent_config_upsert_agents_post

        Agent Config Upsert  # noqa: E501
        """
        pass

    def test_get_list_agents_list_get(self):
        """Test case for get_list_agents_list_get

        Get List  # noqa: E501
        """
        pass

    def test_load_agents_get(self):
        """Test case for load_agents_get

        Load  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
