# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hipai_client
from hipai_client.models.analytics_query import AnalyticsQuery  # noqa: E501
from hipai_client.rest import ApiException


class TestAnalyticsQuery(unittest.TestCase):
    """AnalyticsQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnalyticsQuery(self):
        """Test AnalyticsQuery"""
        # FIXME: construct object with mandatory attributes with example values
        # model = hipai_client.models.analytics_query.AnalyticsQuery()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
