# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hipai_client
from hipai_client.api.team_api import TeamApi  # noqa: E501
from hipai_client.rest import ApiException


class TestTeamApi(unittest.TestCase):
    """TeamApi unit test stubs"""

    def setUp(self):
        self.api = TeamApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_list_team_members_api_team_members_get(self):
        """Test case for list_team_members_api_team_members_get

        List Team Members  # noqa: E501
        """
        pass

    def test_remove_team_member_api_team_members_user_id_delete(self):
        """Test case for remove_team_member_api_team_members_user_id_delete

        Remove Team Member  # noqa: E501
        """
        pass

    def test_reset_user_password_api_team_reset_password_user_id_post(self):
        """Test case for reset_user_password_api_team_reset_password_user_id_post

        Reset User Password  # noqa: E501
        """
        pass

    def test_upsert_team_member_api_team_members_upsert_post(self):
        """Test case for upsert_team_member_api_team_members_upsert_post

        Upsert Team Member  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
