# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hipai_client
from hipai_client.api.data_contexts_api import DataContextsApi  # noqa: E501
from hipai_client.rest import ApiException


class TestDataContextsApi(unittest.TestCase):
    """DataContextsApi unit test stubs"""

    def setUp(self):
        self.api = DataContextsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_build_logs_api_data_contexts_logs_id_get(self):
        """Test case for build_logs_api_data_contexts_logs_id_get

        Build Logs  # noqa: E501
        """
        pass

    def test_delete_data_context_api_data_contexts_id_delete(self):
        """Test case for delete_data_context_api_data_contexts_id_delete

        Delete Data Context  # noqa: E501
        """
        pass

    def test_get_build_options_api_data_contexts_build_options_id_get(self):
        """Test case for get_build_options_api_data_contexts_build_options_id_get

        Get Build Options  # noqa: E501
        """
        pass

    def test_list_data_contexts_api_data_contexts_list_post(self):
        """Test case for list_data_contexts_api_data_contexts_list_post

        List Data Contexts  # noqa: E501
        """
        pass

    def test_load_data_context_api_data_contexts_id_get(self):
        """Test case for load_data_context_api_data_contexts_id_get

        Load Data Context  # noqa: E501
        """
        pass

    def test_load_graph_api_data_contexts_graph_id_get(self):
        """Test case for load_graph_api_data_contexts_graph_id_get

        Load Graph  # noqa: E501
        """
        pass

    def test_upsert_data_context_api_data_contexts_post(self):
        """Test case for upsert_data_context_api_data_contexts_post

        Upsert Data Context  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
