# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hipai_client
from hipai_client.api.evaluations_api import EvaluationsApi  # noqa: E501
from hipai_client.rest import ApiException


class TestEvaluationsApi(unittest.TestCase):
    """EvaluationsApi unit test stubs"""

    def setUp(self):
        self.api = EvaluationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_evaluation_api_evaluations_id_delete(self):
        """Test case for delete_evaluation_api_evaluations_id_delete

        Delete Evaluation  # noqa: E501
        """
        pass

    def test_delete_question_api_evaluations_questions_id_delete(self):
        """Test case for delete_question_api_evaluations_questions_id_delete

        Delete Question  # noqa: E501
        """
        pass

    def test_list_evaluations_api_evaluations_list_get(self):
        """Test case for list_evaluations_api_evaluations_list_get

        List Evaluations  # noqa: E501
        """
        pass

    def test_list_questions_api_evaluations_questions_id_get(self):
        """Test case for list_questions_api_evaluations_questions_id_get

        List Questions  # noqa: E501
        """
        pass

    def test_list_responses_api_evaluations_responses_id_get(self):
        """Test case for list_responses_api_evaluations_responses_id_get

        List Responses  # noqa: E501
        """
        pass

    def test_list_runs_api_evaluations_runs_get(self):
        """Test case for list_runs_api_evaluations_runs_get

        List Runs  # noqa: E501
        """
        pass

    def test_run_evaluation_api_evaluations_run_post(self):
        """Test case for run_evaluation_api_evaluations_run_post

        Run Evaluation  # noqa: E501
        """
        pass

    def test_upsert_evaluation_api_evaluations_post(self):
        """Test case for upsert_evaluation_api_evaluations_post

        Upsert Evaluation  # noqa: E501
        """
        pass

    def test_upsert_question_api_evaluations_question_post(self):
        """Test case for upsert_question_api_evaluations_question_post

        Upsert Question  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
