# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hipai_client
from hipai_client.api.groups_api import GroupsApi  # noqa: E501
from hipai_client.rest import ApiException


class TestGroupsApi(unittest.TestCase):
    """GroupsApi unit test stubs"""

    def setUp(self):
        self.api = GroupsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_group_api_groups_id_delete(self):
        """Test case for delete_group_api_groups_id_delete

        Delete Group  # noqa: E501
        """
        pass

    def test_list_groups_api_groups_list_get(self):
        """Test case for list_groups_api_groups_list_get

        List Groups  # noqa: E501
        """
        pass

    def test_upsert_group_api_groups_post(self):
        """Test case for upsert_group_api_groups_post

        Upsert Group  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
