# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.v1chat_api import V1chatApi  # noqa: E501
from swagger_client.rest import ApiException


class TestV1chatApi(unittest.TestCase):
    """V1chatApi unit test stubs"""

    def setUp(self):
        self.api = V1chatApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_completions_v1_chat_completions_post(self):
        """Test case for completions_v1_chat_completions_post

        Completions  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
