# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hipai_client
from hipai_client.models.any_of_model_config_object_used_by_active_agent import AnyOfModelConfigObjectUsedByActiveAgent  # noqa: E501
from hipai_client.rest import ApiException


class TestAnyOfModelConfigObjectUsedByActiveAgent(unittest.TestCase):
    """AnyOfModelConfigObjectUsedByActiveAgent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnyOfModelConfigObjectUsedByActiveAgent(self):
        """Test AnyOfModelConfigObjectUsedByActiveAgent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = hipai_client.models.any_of_model_config_object_used_by_active_agent.AnyOfModelConfigObjectUsedByActiveAgent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
