# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AgentConfigResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'object',
        'api_key': 'object',
        'name': 'object',
        'active': 'object',
        'updated_at': 'object',
        'llm_config_id': 'object',
        'graph_id': 'object'
    }

    attribute_map = {
        'id': 'id',
        'api_key': 'api_key',
        'name': 'name',
        'active': 'active',
        'updated_at': 'updated_at',
        'llm_config_id': 'llm_config_id',
        'graph_id': 'graph_id'
    }

    def __init__(self, id=None, api_key=None, name=None, active=None, updated_at=None, llm_config_id=None, graph_id=None):  # noqa: E501
        """AgentConfigResponse - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._api_key = None
        self._name = None
        self._active = None
        self._updated_at = None
        self._llm_config_id = None
        self._graph_id = None
        self.discriminator = None
        self.id = id
        self.api_key = api_key
        self.name = name
        self.active = active
        self.updated_at = updated_at
        self.llm_config_id = llm_config_id
        self.graph_id = graph_id

    @property
    def id(self):
        """Gets the id of this AgentConfigResponse.  # noqa: E501


        :return: The id of this AgentConfigResponse.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AgentConfigResponse.


        :param id: The id of this AgentConfigResponse.  # noqa: E501
        :type: object
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def api_key(self):
        """Gets the api_key of this AgentConfigResponse.  # noqa: E501


        :return: The api_key of this AgentConfigResponse.  # noqa: E501
        :rtype: object
        """
        return self._api_key

    @api_key.setter
    def api_key(self, api_key):
        """Sets the api_key of this AgentConfigResponse.


        :param api_key: The api_key of this AgentConfigResponse.  # noqa: E501
        :type: object
        """
        if api_key is None:
            raise ValueError("Invalid value for `api_key`, must not be `None`")  # noqa: E501

        self._api_key = api_key

    @property
    def name(self):
        """Gets the name of this AgentConfigResponse.  # noqa: E501


        :return: The name of this AgentConfigResponse.  # noqa: E501
        :rtype: object
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AgentConfigResponse.


        :param name: The name of this AgentConfigResponse.  # noqa: E501
        :type: object
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def active(self):
        """Gets the active of this AgentConfigResponse.  # noqa: E501


        :return: The active of this AgentConfigResponse.  # noqa: E501
        :rtype: object
        """
        return self._active

    @active.setter
    def active(self, active):
        """Sets the active of this AgentConfigResponse.


        :param active: The active of this AgentConfigResponse.  # noqa: E501
        :type: object
        """
        if active is None:
            raise ValueError("Invalid value for `active`, must not be `None`")  # noqa: E501

        self._active = active

    @property
    def updated_at(self):
        """Gets the updated_at of this AgentConfigResponse.  # noqa: E501


        :return: The updated_at of this AgentConfigResponse.  # noqa: E501
        :rtype: object
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this AgentConfigResponse.


        :param updated_at: The updated_at of this AgentConfigResponse.  # noqa: E501
        :type: object
        """
        if updated_at is None:
            raise ValueError("Invalid value for `updated_at`, must not be `None`")  # noqa: E501

        self._updated_at = updated_at

    @property
    def llm_config_id(self):
        """Gets the llm_config_id of this AgentConfigResponse.  # noqa: E501


        :return: The llm_config_id of this AgentConfigResponse.  # noqa: E501
        :rtype: object
        """
        return self._llm_config_id

    @llm_config_id.setter
    def llm_config_id(self, llm_config_id):
        """Sets the llm_config_id of this AgentConfigResponse.


        :param llm_config_id: The llm_config_id of this AgentConfigResponse.  # noqa: E501
        :type: object
        """
        if llm_config_id is None:
            raise ValueError("Invalid value for `llm_config_id`, must not be `None`")  # noqa: E501

        self._llm_config_id = llm_config_id

    @property
    def graph_id(self):
        """Gets the graph_id of this AgentConfigResponse.  # noqa: E501


        :return: The graph_id of this AgentConfigResponse.  # noqa: E501
        :rtype: object
        """
        return self._graph_id

    @graph_id.setter
    def graph_id(self, graph_id):
        """Sets the graph_id of this AgentConfigResponse.


        :param graph_id: The graph_id of this AgentConfigResponse.  # noqa: E501
        :type: object
        """
        if graph_id is None:
            raise ValueError("Invalid value for `graph_id`, must not be `None`")  # noqa: E501

        self._graph_id = graph_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AgentConfigResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AgentConfigResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
