# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AgentConfigObject(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'object',
        'status': 'object',
        'id': 'object',
        'updated_at': 'object',
        'api_key': 'object',
        'llm_config_id': 'object',
        'graph_id': 'object',
        'group_id': 'object'
    }

    attribute_map = {
        'name': 'name',
        'status': 'status',
        'id': 'id',
        'updated_at': 'updated_at',
        'api_key': 'api_key',
        'llm_config_id': 'llm_config_id',
        'graph_id': 'graph_id',
        'group_id': 'group_id'
    }

    def __init__(self, name=None, status=None, id=None, updated_at=None, api_key=None, llm_config_id=None, graph_id=None, group_id=None):  # noqa: E501
        """AgentConfigObject - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._status = None
        self._id = None
        self._updated_at = None
        self._api_key = None
        self._llm_config_id = None
        self._graph_id = None
        self._group_id = None
        self.discriminator = None
        self.name = name
        self.status = status
        if id is not None:
            self.id = id
        if updated_at is not None:
            self.updated_at = updated_at
        if api_key is not None:
            self.api_key = api_key
        if llm_config_id is not None:
            self.llm_config_id = llm_config_id
        if graph_id is not None:
            self.graph_id = graph_id
        if group_id is not None:
            self.group_id = group_id

    @property
    def name(self):
        """Gets the name of this AgentConfigObject.  # noqa: E501


        :return: The name of this AgentConfigObject.  # noqa: E501
        :rtype: object
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AgentConfigObject.


        :param name: The name of this AgentConfigObject.  # noqa: E501
        :type: object
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def status(self):
        """Gets the status of this AgentConfigObject.  # noqa: E501


        :return: The status of this AgentConfigObject.  # noqa: E501
        :rtype: object
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this AgentConfigObject.


        :param status: The status of this AgentConfigObject.  # noqa: E501
        :type: object
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def id(self):
        """Gets the id of this AgentConfigObject.  # noqa: E501


        :return: The id of this AgentConfigObject.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AgentConfigObject.


        :param id: The id of this AgentConfigObject.  # noqa: E501
        :type: object
        """

        self._id = id

    @property
    def updated_at(self):
        """Gets the updated_at of this AgentConfigObject.  # noqa: E501


        :return: The updated_at of this AgentConfigObject.  # noqa: E501
        :rtype: object
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this AgentConfigObject.


        :param updated_at: The updated_at of this AgentConfigObject.  # noqa: E501
        :type: object
        """

        self._updated_at = updated_at

    @property
    def api_key(self):
        """Gets the api_key of this AgentConfigObject.  # noqa: E501


        :return: The api_key of this AgentConfigObject.  # noqa: E501
        :rtype: object
        """
        return self._api_key

    @api_key.setter
    def api_key(self, api_key):
        """Sets the api_key of this AgentConfigObject.


        :param api_key: The api_key of this AgentConfigObject.  # noqa: E501
        :type: object
        """

        self._api_key = api_key

    @property
    def llm_config_id(self):
        """Gets the llm_config_id of this AgentConfigObject.  # noqa: E501


        :return: The llm_config_id of this AgentConfigObject.  # noqa: E501
        :rtype: object
        """
        return self._llm_config_id

    @llm_config_id.setter
    def llm_config_id(self, llm_config_id):
        """Sets the llm_config_id of this AgentConfigObject.


        :param llm_config_id: The llm_config_id of this AgentConfigObject.  # noqa: E501
        :type: object
        """

        self._llm_config_id = llm_config_id

    @property
    def graph_id(self):
        """Gets the graph_id of this AgentConfigObject.  # noqa: E501


        :return: The graph_id of this AgentConfigObject.  # noqa: E501
        :rtype: object
        """
        return self._graph_id

    @graph_id.setter
    def graph_id(self, graph_id):
        """Sets the graph_id of this AgentConfigObject.


        :param graph_id: The graph_id of this AgentConfigObject.  # noqa: E501
        :type: object
        """

        self._graph_id = graph_id

    @property
    def group_id(self):
        """Gets the group_id of this AgentConfigObject.  # noqa: E501


        :return: The group_id of this AgentConfigObject.  # noqa: E501
        :rtype: object
        """
        return self._group_id

    @group_id.setter
    def group_id(self, group_id):
        """Sets the group_id of this AgentConfigObject.


        :param group_id: The group_id of this AgentConfigObject.  # noqa: E501
        :type: object
        """

        self._group_id = group_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AgentConfigObject, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AgentConfigObject):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
