# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AgentConfigObject(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'object',
        'active': 'object',
        'id': 'object',
        'llm_config_id': 'object',
        'graph_id': 'object'
    }

    attribute_map = {
        'name': 'name',
        'active': 'active',
        'id': 'id',
        'llm_config_id': 'llm_config_id',
        'graph_id': 'graph_id'
    }

    def __init__(self, name=None, active=None, id=None, llm_config_id=None, graph_id=None):  # noqa: E501
        """AgentConfigObject - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._active = None
        self._id = None
        self._llm_config_id = None
        self._graph_id = None
        self.discriminator = None
        self.name = name
        self.active = active
        if id is not None:
            self.id = id
        if llm_config_id is not None:
            self.llm_config_id = llm_config_id
        if graph_id is not None:
            self.graph_id = graph_id

    @property
    def name(self):
        """Gets the name of this AgentConfigObject.  # noqa: E501


        :return: The name of this AgentConfigObject.  # noqa: E501
        :rtype: object
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AgentConfigObject.


        :param name: The name of this AgentConfigObject.  # noqa: E501
        :type: object
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def active(self):
        """Gets the active of this AgentConfigObject.  # noqa: E501


        :return: The active of this AgentConfigObject.  # noqa: E501
        :rtype: object
        """
        return self._active

    @active.setter
    def active(self, active):
        """Sets the active of this AgentConfigObject.


        :param active: The active of this AgentConfigObject.  # noqa: E501
        :type: object
        """
        if active is None:
            raise ValueError("Invalid value for `active`, must not be `None`")  # noqa: E501

        self._active = active

    @property
    def id(self):
        """Gets the id of this AgentConfigObject.  # noqa: E501


        :return: The id of this AgentConfigObject.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AgentConfigObject.


        :param id: The id of this AgentConfigObject.  # noqa: E501
        :type: object
        """

        self._id = id

    @property
    def llm_config_id(self):
        """Gets the llm_config_id of this AgentConfigObject.  # noqa: E501


        :return: The llm_config_id of this AgentConfigObject.  # noqa: E501
        :rtype: object
        """
        return self._llm_config_id

    @llm_config_id.setter
    def llm_config_id(self, llm_config_id):
        """Sets the llm_config_id of this AgentConfigObject.


        :param llm_config_id: The llm_config_id of this AgentConfigObject.  # noqa: E501
        :type: object
        """

        self._llm_config_id = llm_config_id

    @property
    def graph_id(self):
        """Gets the graph_id of this AgentConfigObject.  # noqa: E501


        :return: The graph_id of this AgentConfigObject.  # noqa: E501
        :rtype: object
        """
        return self._graph_id

    @graph_id.setter
    def graph_id(self, graph_id):
        """Sets the graph_id of this AgentConfigObject.


        :param graph_id: The graph_id of this AgentConfigObject.  # noqa: E501
        :type: object
        """

        self._graph_id = graph_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AgentConfigObject, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AgentConfigObject):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
