# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AnalyticsResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'total_tokens': 'object',
        'total_tokens_build': 'object',
        'total_requests': 'object',
        'requests': 'object',
        'tokens': 'object',
        'tokens_build': 'object',
        'response_times': 'object'
    }

    attribute_map = {
        'total_tokens': 'total_tokens',
        'total_tokens_build': 'total_tokens_build',
        'total_requests': 'total_requests',
        'requests': 'requests',
        'tokens': 'tokens',
        'tokens_build': 'tokens_build',
        'response_times': 'response_times'
    }

    def __init__(self, total_tokens=None, total_tokens_build=None, total_requests=None, requests=None, tokens=None, tokens_build=None, response_times=None):  # noqa: E501
        """AnalyticsResponse - a model defined in Swagger"""  # noqa: E501
        self._total_tokens = None
        self._total_tokens_build = None
        self._total_requests = None
        self._requests = None
        self._tokens = None
        self._tokens_build = None
        self._response_times = None
        self.discriminator = None
        self.total_tokens = total_tokens
        self.total_tokens_build = total_tokens_build
        self.total_requests = total_requests
        self.requests = requests
        self.tokens = tokens
        self.tokens_build = tokens_build
        self.response_times = response_times

    @property
    def total_tokens(self):
        """Gets the total_tokens of this AnalyticsResponse.  # noqa: E501


        :return: The total_tokens of this AnalyticsResponse.  # noqa: E501
        :rtype: object
        """
        return self._total_tokens

    @total_tokens.setter
    def total_tokens(self, total_tokens):
        """Sets the total_tokens of this AnalyticsResponse.


        :param total_tokens: The total_tokens of this AnalyticsResponse.  # noqa: E501
        :type: object
        """
        if total_tokens is None:
            raise ValueError("Invalid value for `total_tokens`, must not be `None`")  # noqa: E501

        self._total_tokens = total_tokens

    @property
    def total_tokens_build(self):
        """Gets the total_tokens_build of this AnalyticsResponse.  # noqa: E501


        :return: The total_tokens_build of this AnalyticsResponse.  # noqa: E501
        :rtype: object
        """
        return self._total_tokens_build

    @total_tokens_build.setter
    def total_tokens_build(self, total_tokens_build):
        """Sets the total_tokens_build of this AnalyticsResponse.


        :param total_tokens_build: The total_tokens_build of this AnalyticsResponse.  # noqa: E501
        :type: object
        """
        if total_tokens_build is None:
            raise ValueError("Invalid value for `total_tokens_build`, must not be `None`")  # noqa: E501

        self._total_tokens_build = total_tokens_build

    @property
    def total_requests(self):
        """Gets the total_requests of this AnalyticsResponse.  # noqa: E501


        :return: The total_requests of this AnalyticsResponse.  # noqa: E501
        :rtype: object
        """
        return self._total_requests

    @total_requests.setter
    def total_requests(self, total_requests):
        """Sets the total_requests of this AnalyticsResponse.


        :param total_requests: The total_requests of this AnalyticsResponse.  # noqa: E501
        :type: object
        """
        if total_requests is None:
            raise ValueError("Invalid value for `total_requests`, must not be `None`")  # noqa: E501

        self._total_requests = total_requests

    @property
    def requests(self):
        """Gets the requests of this AnalyticsResponse.  # noqa: E501


        :return: The requests of this AnalyticsResponse.  # noqa: E501
        :rtype: object
        """
        return self._requests

    @requests.setter
    def requests(self, requests):
        """Sets the requests of this AnalyticsResponse.


        :param requests: The requests of this AnalyticsResponse.  # noqa: E501
        :type: object
        """
        if requests is None:
            raise ValueError("Invalid value for `requests`, must not be `None`")  # noqa: E501

        self._requests = requests

    @property
    def tokens(self):
        """Gets the tokens of this AnalyticsResponse.  # noqa: E501


        :return: The tokens of this AnalyticsResponse.  # noqa: E501
        :rtype: object
        """
        return self._tokens

    @tokens.setter
    def tokens(self, tokens):
        """Sets the tokens of this AnalyticsResponse.


        :param tokens: The tokens of this AnalyticsResponse.  # noqa: E501
        :type: object
        """
        if tokens is None:
            raise ValueError("Invalid value for `tokens`, must not be `None`")  # noqa: E501

        self._tokens = tokens

    @property
    def tokens_build(self):
        """Gets the tokens_build of this AnalyticsResponse.  # noqa: E501


        :return: The tokens_build of this AnalyticsResponse.  # noqa: E501
        :rtype: object
        """
        return self._tokens_build

    @tokens_build.setter
    def tokens_build(self, tokens_build):
        """Sets the tokens_build of this AnalyticsResponse.


        :param tokens_build: The tokens_build of this AnalyticsResponse.  # noqa: E501
        :type: object
        """
        if tokens_build is None:
            raise ValueError("Invalid value for `tokens_build`, must not be `None`")  # noqa: E501

        self._tokens_build = tokens_build

    @property
    def response_times(self):
        """Gets the response_times of this AnalyticsResponse.  # noqa: E501


        :return: The response_times of this AnalyticsResponse.  # noqa: E501
        :rtype: object
        """
        return self._response_times

    @response_times.setter
    def response_times(self, response_times):
        """Sets the response_times of this AnalyticsResponse.


        :param response_times: The response_times of this AnalyticsResponse.  # noqa: E501
        :type: object
        """
        if response_times is None:
            raise ValueError("Invalid value for `response_times`, must not be `None`")  # noqa: E501

        self._response_times = response_times

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AnalyticsResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AnalyticsResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
