# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AnalyticsQuery(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'days': 'object',
        'tz_offset': 'object',
        'agent_config_id': 'object',
        'llm_config_id': 'object',
        'all': 'object'
    }

    attribute_map = {
        'days': 'days',
        'tz_offset': 'tz_offset',
        'agent_config_id': 'agent_config_id',
        'llm_config_id': 'llm_config_id',
        'all': 'all'
    }

    def __init__(self, days=None, tz_offset=None, agent_config_id=None, llm_config_id=None, all=None):  # noqa: E501
        """AnalyticsQuery - a model defined in Swagger"""  # noqa: E501
        self._days = None
        self._tz_offset = None
        self._agent_config_id = None
        self._llm_config_id = None
        self._all = None
        self.discriminator = None
        self.days = days
        if tz_offset is not None:
            self.tz_offset = tz_offset
        if agent_config_id is not None:
            self.agent_config_id = agent_config_id
        if llm_config_id is not None:
            self.llm_config_id = llm_config_id
        if all is not None:
            self.all = all

    @property
    def days(self):
        """Gets the days of this AnalyticsQuery.  # noqa: E501


        :return: The days of this AnalyticsQuery.  # noqa: E501
        :rtype: object
        """
        return self._days

    @days.setter
    def days(self, days):
        """Sets the days of this AnalyticsQuery.


        :param days: The days of this AnalyticsQuery.  # noqa: E501
        :type: object
        """
        if days is None:
            raise ValueError("Invalid value for `days`, must not be `None`")  # noqa: E501

        self._days = days

    @property
    def tz_offset(self):
        """Gets the tz_offset of this AnalyticsQuery.  # noqa: E501


        :return: The tz_offset of this AnalyticsQuery.  # noqa: E501
        :rtype: object
        """
        return self._tz_offset

    @tz_offset.setter
    def tz_offset(self, tz_offset):
        """Sets the tz_offset of this AnalyticsQuery.


        :param tz_offset: The tz_offset of this AnalyticsQuery.  # noqa: E501
        :type: object
        """

        self._tz_offset = tz_offset

    @property
    def agent_config_id(self):
        """Gets the agent_config_id of this AnalyticsQuery.  # noqa: E501


        :return: The agent_config_id of this AnalyticsQuery.  # noqa: E501
        :rtype: object
        """
        return self._agent_config_id

    @agent_config_id.setter
    def agent_config_id(self, agent_config_id):
        """Sets the agent_config_id of this AnalyticsQuery.


        :param agent_config_id: The agent_config_id of this AnalyticsQuery.  # noqa: E501
        :type: object
        """

        self._agent_config_id = agent_config_id

    @property
    def llm_config_id(self):
        """Gets the llm_config_id of this AnalyticsQuery.  # noqa: E501


        :return: The llm_config_id of this AnalyticsQuery.  # noqa: E501
        :rtype: object
        """
        return self._llm_config_id

    @llm_config_id.setter
    def llm_config_id(self, llm_config_id):
        """Sets the llm_config_id of this AnalyticsQuery.


        :param llm_config_id: The llm_config_id of this AnalyticsQuery.  # noqa: E501
        :type: object
        """

        self._llm_config_id = llm_config_id

    @property
    def all(self):
        """Gets the all of this AnalyticsQuery.  # noqa: E501


        :return: The all of this AnalyticsQuery.  # noqa: E501
        :rtype: object
        """
        return self._all

    @all.setter
    def all(self, all):
        """Sets the all of this AnalyticsQuery.


        :param all: The all of this AnalyticsQuery.  # noqa: E501
        :type: object
        """

        self._all = all

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AnalyticsQuery, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AnalyticsQuery):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
