# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Annotation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'object',
        'url_citation': 'AnnotationURLCitation'
    }

    attribute_map = {
        'type': 'type',
        'url_citation': 'url_citation'
    }

    def __init__(self, type=None, url_citation=None):  # noqa: E501
        """Annotation - a model defined in Swagger"""  # noqa: E501
        self._type = None
        self._url_citation = None
        self.discriminator = None
        self.type = type
        self.url_citation = url_citation

    @property
    def type(self):
        """Gets the type of this Annotation.  # noqa: E501


        :return: The type of this Annotation.  # noqa: E501
        :rtype: object
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Annotation.


        :param type: The type of this Annotation.  # noqa: E501
        :type: object
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def url_citation(self):
        """Gets the url_citation of this Annotation.  # noqa: E501


        :return: The url_citation of this Annotation.  # noqa: E501
        :rtype: AnnotationURLCitation
        """
        return self._url_citation

    @url_citation.setter
    def url_citation(self, url_citation):
        """Sets the url_citation of this Annotation.


        :param url_citation: The url_citation of this Annotation.  # noqa: E501
        :type: AnnotationURLCitation
        """
        if url_citation is None:
            raise ValueError("Invalid value for `url_citation`, must not be `None`")  # noqa: E501

        self._url_citation = url_citation

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Annotation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Annotation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
