# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AnnotationURLCitation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'end_index': 'object',
        'start_index': 'object',
        'title': 'object',
        'url': 'object'
    }

    attribute_map = {
        'end_index': 'end_index',
        'start_index': 'start_index',
        'title': 'title',
        'url': 'url'
    }

    def __init__(self, end_index=None, start_index=None, title=None, url=None):  # noqa: E501
        """AnnotationURLCitation - a model defined in Swagger"""  # noqa: E501
        self._end_index = None
        self._start_index = None
        self._title = None
        self._url = None
        self.discriminator = None
        self.end_index = end_index
        self.start_index = start_index
        self.title = title
        self.url = url

    @property
    def end_index(self):
        """Gets the end_index of this AnnotationURLCitation.  # noqa: E501


        :return: The end_index of this AnnotationURLCitation.  # noqa: E501
        :rtype: object
        """
        return self._end_index

    @end_index.setter
    def end_index(self, end_index):
        """Sets the end_index of this AnnotationURLCitation.


        :param end_index: The end_index of this AnnotationURLCitation.  # noqa: E501
        :type: object
        """
        if end_index is None:
            raise ValueError("Invalid value for `end_index`, must not be `None`")  # noqa: E501

        self._end_index = end_index

    @property
    def start_index(self):
        """Gets the start_index of this AnnotationURLCitation.  # noqa: E501


        :return: The start_index of this AnnotationURLCitation.  # noqa: E501
        :rtype: object
        """
        return self._start_index

    @start_index.setter
    def start_index(self, start_index):
        """Sets the start_index of this AnnotationURLCitation.


        :param start_index: The start_index of this AnnotationURLCitation.  # noqa: E501
        :type: object
        """
        if start_index is None:
            raise ValueError("Invalid value for `start_index`, must not be `None`")  # noqa: E501

        self._start_index = start_index

    @property
    def title(self):
        """Gets the title of this AnnotationURLCitation.  # noqa: E501


        :return: The title of this AnnotationURLCitation.  # noqa: E501
        :rtype: object
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this AnnotationURLCitation.


        :param title: The title of this AnnotationURLCitation.  # noqa: E501
        :type: object
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def url(self):
        """Gets the url of this AnnotationURLCitation.  # noqa: E501


        :return: The url of this AnnotationURLCitation.  # noqa: E501
        :rtype: object
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this AnnotationURLCitation.


        :param url: The url of this AnnotationURLCitation.  # noqa: E501
        :type: object
        """
        if url is None:
            raise ValueError("Invalid value for `url`, must not be `None`")  # noqa: E501

        self._url = url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AnnotationURLCitation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AnnotationURLCitation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
