# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BuildOptionsObject(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'project_id': 'object',
        'id': 'object',
        'graph_id': 'object',
        'evaluation_id': 'object',
        'graph_structure_prompt': 'object',
        'file_import_prompt': 'object',
        'sql_import_prompt': 'object',
        'low_precision': 'object',
        'domain': 'object'
    }

    attribute_map = {
        'project_id': 'project_id',
        'id': 'id',
        'graph_id': 'graph_id',
        'evaluation_id': 'evaluation_id',
        'graph_structure_prompt': 'graph_structure_prompt',
        'file_import_prompt': 'file_import_prompt',
        'sql_import_prompt': 'sql_import_prompt',
        'low_precision': 'low_precision',
        'domain': 'domain'
    }

    def __init__(self, project_id=None, id=None, graph_id=None, evaluation_id=None, graph_structure_prompt=None, file_import_prompt=None, sql_import_prompt=None, low_precision=None, domain=None, *args, **kwargs):  # noqa: E501
        """BuildOptionsObject - a model defined in Swagger"""  # noqa: E501
        self._project_id = None
        self._id = None
        self._graph_id = None
        self._evaluation_id = None
        self._graph_structure_prompt = None
        self._file_import_prompt = None
        self._sql_import_prompt = None
        self._low_precision = None
        self._domain = None
        self.discriminator = None
        if project_id is not None:
            self.project_id = project_id
        if id is not None:
            self.id = id
        if graph_id is not None:
            self.graph_id = graph_id
        if evaluation_id is not None:
            self.evaluation_id = evaluation_id
        if graph_structure_prompt is not None:
            self.graph_structure_prompt = graph_structure_prompt
        if file_import_prompt is not None:
            self.file_import_prompt = file_import_prompt
        if sql_import_prompt is not None:
            self.sql_import_prompt = sql_import_prompt
        if low_precision is not None:
            self.low_precision = low_precision
        if domain is not None:
            self.domain = domain

    @property
    def project_id(self):
        """Gets the project_id of this BuildOptionsObject.  # noqa: E501


        :return: The project_id of this BuildOptionsObject.  # noqa: E501
        :rtype: object
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this BuildOptionsObject.


        :param project_id: The project_id of this BuildOptionsObject.  # noqa: E501
        :type: object
        """

        self._project_id = project_id

    @property
    def id(self):
        """Gets the id of this BuildOptionsObject.  # noqa: E501


        :return: The id of this BuildOptionsObject.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this BuildOptionsObject.


        :param id: The id of this BuildOptionsObject.  # noqa: E501
        :type: object
        """

        self._id = id

    @property
    def graph_id(self):
        """Gets the graph_id of this BuildOptionsObject.  # noqa: E501


        :return: The graph_id of this BuildOptionsObject.  # noqa: E501
        :rtype: object
        """
        return self._graph_id

    @graph_id.setter
    def graph_id(self, graph_id):
        """Sets the graph_id of this BuildOptionsObject.


        :param graph_id: The graph_id of this BuildOptionsObject.  # noqa: E501
        :type: object
        """

        self._graph_id = graph_id

    @property
    def evaluation_id(self):
        """Gets the evaluation_id of this BuildOptionsObject.  # noqa: E501


        :return: The evaluation_id of this BuildOptionsObject.  # noqa: E501
        :rtype: object
        """
        return self._evaluation_id

    @evaluation_id.setter
    def evaluation_id(self, evaluation_id):
        """Sets the evaluation_id of this BuildOptionsObject.


        :param evaluation_id: The evaluation_id of this BuildOptionsObject.  # noqa: E501
        :type: object
        """

        self._evaluation_id = evaluation_id

    @property
    def graph_structure_prompt(self):
        """Gets the graph_structure_prompt of this BuildOptionsObject.  # noqa: E501


        :return: The graph_structure_prompt of this BuildOptionsObject.  # noqa: E501
        :rtype: object
        """
        return self._graph_structure_prompt

    @graph_structure_prompt.setter
    def graph_structure_prompt(self, graph_structure_prompt):
        """Sets the graph_structure_prompt of this BuildOptionsObject.


        :param graph_structure_prompt: The graph_structure_prompt of this BuildOptionsObject.  # noqa: E501
        :type: object
        """

        self._graph_structure_prompt = graph_structure_prompt

    @property
    def file_import_prompt(self):
        """Gets the file_import_prompt of this BuildOptionsObject.  # noqa: E501


        :return: The file_import_prompt of this BuildOptionsObject.  # noqa: E501
        :rtype: object
        """
        return self._file_import_prompt

    @file_import_prompt.setter
    def file_import_prompt(self, file_import_prompt):
        """Sets the file_import_prompt of this BuildOptionsObject.


        :param file_import_prompt: The file_import_prompt of this BuildOptionsObject.  # noqa: E501
        :type: object
        """

        self._file_import_prompt = file_import_prompt

    @property
    def sql_import_prompt(self):
        """Gets the sql_import_prompt of this BuildOptionsObject.  # noqa: E501


        :return: The sql_import_prompt of this BuildOptionsObject.  # noqa: E501
        :rtype: object
        """
        return self._sql_import_prompt

    @sql_import_prompt.setter
    def sql_import_prompt(self, sql_import_prompt):
        """Sets the sql_import_prompt of this BuildOptionsObject.


        :param sql_import_prompt: The sql_import_prompt of this BuildOptionsObject.  # noqa: E501
        :type: object
        """

        self._sql_import_prompt = sql_import_prompt

    @property
    def low_precision(self):
        """Gets the low_precision of this BuildOptionsObject.  # noqa: E501


        :return: The low_precision of this BuildOptionsObject.  # noqa: E501
        :rtype: object
        """
        return self._low_precision

    @low_precision.setter
    def low_precision(self, low_precision):
        """Sets the low_precision of this BuildOptionsObject.


        :param low_precision: The low_precision of this BuildOptionsObject.  # noqa: E501
        :type: object
        """

        self._low_precision = low_precision

    @property
    def domain(self):
        """Gets the domain of this BuildOptionsObject.  # noqa: E501


        :return: The domain of this BuildOptionsObject.  # noqa: E501
        :rtype: object
        """
        return self._domain

    @domain.setter
    def domain(self, domain):
        """Sets the domain of this BuildOptionsObject.


        :param domain: The domain of this BuildOptionsObject.  # noqa: E501
        :type: object
        """

        self._domain = domain

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BuildOptionsObject, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BuildOptionsObject):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
