# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ChatCompletionRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'messages': 'object',
        'llm_config_id': 'object',
        'agent_id': 'object',
        'agent_api_key': 'object',
        'graph_id': 'object',
        'extras': 'object',
        'model': 'object'
    }

    attribute_map = {
        'messages': 'messages',
        'llm_config_id': 'llm_config_id',
        'agent_id': 'agent_id',
        'agent_api_key': 'agent_api_key',
        'graph_id': 'graph_id',
        'extras': 'extras',
        'model': 'model'
    }

    def __init__(self, messages=None, llm_config_id=None, agent_id=None, agent_api_key=None, graph_id=None, extras=None, model=None):  # noqa: E501
        """ChatCompletionRequest - a model defined in Swagger"""  # noqa: E501
        self._messages = None
        self._llm_config_id = None
        self._agent_id = None
        self._agent_api_key = None
        self._graph_id = None
        self._extras = None
        self._model = None
        self.discriminator = None
        self.messages = messages
        if llm_config_id is not None:
            self.llm_config_id = llm_config_id
        if agent_id is not None:
            self.agent_id = agent_id
        if agent_api_key is not None:
            self.agent_api_key = agent_api_key
        if graph_id is not None:
            self.graph_id = graph_id
        if extras is not None:
            self.extras = extras
        if model is not None:
            self.model = model

    @property
    def messages(self):
        """Gets the messages of this ChatCompletionRequest.  # noqa: E501


        :return: The messages of this ChatCompletionRequest.  # noqa: E501
        :rtype: object
        """
        return self._messages

    @messages.setter
    def messages(self, messages):
        """Sets the messages of this ChatCompletionRequest.


        :param messages: The messages of this ChatCompletionRequest.  # noqa: E501
        :type: object
        """
        if messages is None:
            raise ValueError("Invalid value for `messages`, must not be `None`")  # noqa: E501

        self._messages = messages

    @property
    def llm_config_id(self):
        """Gets the llm_config_id of this ChatCompletionRequest.  # noqa: E501


        :return: The llm_config_id of this ChatCompletionRequest.  # noqa: E501
        :rtype: object
        """
        return self._llm_config_id

    @llm_config_id.setter
    def llm_config_id(self, llm_config_id):
        """Sets the llm_config_id of this ChatCompletionRequest.


        :param llm_config_id: The llm_config_id of this ChatCompletionRequest.  # noqa: E501
        :type: object
        """

        self._llm_config_id = llm_config_id

    @property
    def agent_id(self):
        """Gets the agent_id of this ChatCompletionRequest.  # noqa: E501


        :return: The agent_id of this ChatCompletionRequest.  # noqa: E501
        :rtype: object
        """
        return self._agent_id

    @agent_id.setter
    def agent_id(self, agent_id):
        """Sets the agent_id of this ChatCompletionRequest.


        :param agent_id: The agent_id of this ChatCompletionRequest.  # noqa: E501
        :type: object
        """

        self._agent_id = agent_id

    @property
    def agent_api_key(self):
        """Gets the agent_api_key of this ChatCompletionRequest.  # noqa: E501


        :return: The agent_api_key of this ChatCompletionRequest.  # noqa: E501
        :rtype: object
        """
        return self._agent_api_key

    @agent_api_key.setter
    def agent_api_key(self, agent_api_key):
        """Sets the agent_api_key of this ChatCompletionRequest.


        :param agent_api_key: The agent_api_key of this ChatCompletionRequest.  # noqa: E501
        :type: object
        """

        self._agent_api_key = agent_api_key

    @property
    def graph_id(self):
        """Gets the graph_id of this ChatCompletionRequest.  # noqa: E501


        :return: The graph_id of this ChatCompletionRequest.  # noqa: E501
        :rtype: object
        """
        return self._graph_id

    @graph_id.setter
    def graph_id(self, graph_id):
        """Sets the graph_id of this ChatCompletionRequest.


        :param graph_id: The graph_id of this ChatCompletionRequest.  # noqa: E501
        :type: object
        """

        self._graph_id = graph_id

    @property
    def extras(self):
        """Gets the extras of this ChatCompletionRequest.  # noqa: E501


        :return: The extras of this ChatCompletionRequest.  # noqa: E501
        :rtype: object
        """
        return self._extras

    @extras.setter
    def extras(self, extras):
        """Sets the extras of this ChatCompletionRequest.


        :param extras: The extras of this ChatCompletionRequest.  # noqa: E501
        :type: object
        """

        self._extras = extras

    @property
    def model(self):
        """Gets the model of this ChatCompletionRequest.  # noqa: E501


        :return: The model of this ChatCompletionRequest.  # noqa: E501
        :rtype: object
        """
        return self._model

    @model.setter
    def model(self, model):
        """Sets the model of this ChatCompletionRequest.


        :param model: The model of this ChatCompletionRequest.  # noqa: E501
        :type: object
        """

        self._model = model

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ChatCompletionRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ChatCompletionRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
