# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ChatMessageOutput(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'role': 'object',
        'content': 'object',
        'reasoning_content': 'object',
        'tool_call_id': 'object',
        'tool_calls': 'object'
    }

    attribute_map = {
        'role': 'role',
        'content': 'content',
        'reasoning_content': 'reasoning_content',
        'tool_call_id': 'tool_call_id',
        'tool_calls': 'tool_calls'
    }

    def __init__(self, role=None, content=None, reasoning_content=None, tool_call_id=None, tool_calls=None):  # noqa: E501
        """ChatMessageOutput - a model defined in Swagger"""  # noqa: E501
        self._role = None
        self._content = None
        self._reasoning_content = None
        self._tool_call_id = None
        self._tool_calls = None
        self.discriminator = None
        self.role = role
        if content is not None:
            self.content = content
        if reasoning_content is not None:
            self.reasoning_content = reasoning_content
        if tool_call_id is not None:
            self.tool_call_id = tool_call_id
        if tool_calls is not None:
            self.tool_calls = tool_calls

    @property
    def role(self):
        """Gets the role of this ChatMessageOutput.  # noqa: E501


        :return: The role of this ChatMessageOutput.  # noqa: E501
        :rtype: object
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this ChatMessageOutput.


        :param role: The role of this ChatMessageOutput.  # noqa: E501
        :type: object
        """
        if role is None:
            raise ValueError("Invalid value for `role`, must not be `None`")  # noqa: E501

        self._role = role

    @property
    def content(self):
        """Gets the content of this ChatMessageOutput.  # noqa: E501


        :return: The content of this ChatMessageOutput.  # noqa: E501
        :rtype: object
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this ChatMessageOutput.


        :param content: The content of this ChatMessageOutput.  # noqa: E501
        :type: object
        """

        self._content = content

    @property
    def reasoning_content(self):
        """Gets the reasoning_content of this ChatMessageOutput.  # noqa: E501


        :return: The reasoning_content of this ChatMessageOutput.  # noqa: E501
        :rtype: object
        """
        return self._reasoning_content

    @reasoning_content.setter
    def reasoning_content(self, reasoning_content):
        """Sets the reasoning_content of this ChatMessageOutput.


        :param reasoning_content: The reasoning_content of this ChatMessageOutput.  # noqa: E501
        :type: object
        """

        self._reasoning_content = reasoning_content

    @property
    def tool_call_id(self):
        """Gets the tool_call_id of this ChatMessageOutput.  # noqa: E501


        :return: The tool_call_id of this ChatMessageOutput.  # noqa: E501
        :rtype: object
        """
        return self._tool_call_id

    @tool_call_id.setter
    def tool_call_id(self, tool_call_id):
        """Sets the tool_call_id of this ChatMessageOutput.


        :param tool_call_id: The tool_call_id of this ChatMessageOutput.  # noqa: E501
        :type: object
        """

        self._tool_call_id = tool_call_id

    @property
    def tool_calls(self):
        """Gets the tool_calls of this ChatMessageOutput.  # noqa: E501


        :return: The tool_calls of this ChatMessageOutput.  # noqa: E501
        :rtype: object
        """
        return self._tool_calls

    @tool_calls.setter
    def tool_calls(self, tool_calls):
        """Sets the tool_calls of this ChatMessageOutput.


        :param tool_calls: The tool_calls of this ChatMessageOutput.  # noqa: E501
        :type: object
        """

        self._tool_calls = tool_calls

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ChatMessageOutput, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ChatMessageOutput):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
