# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ChatCompletion(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'object',
        'choices': 'object',
        'created': 'object',
        'model': 'object',
        'object': 'object',
        'service_tier': 'object',
        'system_fingerprint': 'object',
        'usage': 'object'
    }

    attribute_map = {
        'id': 'id',
        'choices': 'choices',
        'created': 'created',
        'model': 'model',
        'object': 'object',
        'service_tier': 'service_tier',
        'system_fingerprint': 'system_fingerprint',
        'usage': 'usage'
    }

    def __init__(self, id=None, choices=None, created=None, model=None, object=None, service_tier=None, system_fingerprint=None, usage=None):  # noqa: E501
        """ChatCompletion - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._choices = None
        self._created = None
        self._model = None
        self._object = None
        self._service_tier = None
        self._system_fingerprint = None
        self._usage = None
        self.discriminator = None
        self.id = id
        self.choices = choices
        self.created = created
        self.model = model
        self.object = object
        if service_tier is not None:
            self.service_tier = service_tier
        if system_fingerprint is not None:
            self.system_fingerprint = system_fingerprint
        if usage is not None:
            self.usage = usage

    @property
    def id(self):
        """Gets the id of this ChatCompletion.  # noqa: E501


        :return: The id of this ChatCompletion.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ChatCompletion.


        :param id: The id of this ChatCompletion.  # noqa: E501
        :type: object
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def choices(self):
        """Gets the choices of this ChatCompletion.  # noqa: E501


        :return: The choices of this ChatCompletion.  # noqa: E501
        :rtype: object
        """
        return self._choices

    @choices.setter
    def choices(self, choices):
        """Sets the choices of this ChatCompletion.


        :param choices: The choices of this ChatCompletion.  # noqa: E501
        :type: object
        """
        if choices is None:
            raise ValueError("Invalid value for `choices`, must not be `None`")  # noqa: E501

        self._choices = choices

    @property
    def created(self):
        """Gets the created of this ChatCompletion.  # noqa: E501


        :return: The created of this ChatCompletion.  # noqa: E501
        :rtype: object
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this ChatCompletion.


        :param created: The created of this ChatCompletion.  # noqa: E501
        :type: object
        """
        if created is None:
            raise ValueError("Invalid value for `created`, must not be `None`")  # noqa: E501

        self._created = created

    @property
    def model(self):
        """Gets the model of this ChatCompletion.  # noqa: E501


        :return: The model of this ChatCompletion.  # noqa: E501
        :rtype: object
        """
        return self._model

    @model.setter
    def model(self, model):
        """Sets the model of this ChatCompletion.


        :param model: The model of this ChatCompletion.  # noqa: E501
        :type: object
        """
        if model is None:
            raise ValueError("Invalid value for `model`, must not be `None`")  # noqa: E501

        self._model = model

    @property
    def object(self):
        """Gets the object of this ChatCompletion.  # noqa: E501


        :return: The object of this ChatCompletion.  # noqa: E501
        :rtype: object
        """
        return self._object

    @object.setter
    def object(self, object):
        """Sets the object of this ChatCompletion.


        :param object: The object of this ChatCompletion.  # noqa: E501
        :type: object
        """
        if object is None:
            raise ValueError("Invalid value for `object`, must not be `None`")  # noqa: E501

        self._object = object

    @property
    def service_tier(self):
        """Gets the service_tier of this ChatCompletion.  # noqa: E501


        :return: The service_tier of this ChatCompletion.  # noqa: E501
        :rtype: object
        """
        return self._service_tier

    @service_tier.setter
    def service_tier(self, service_tier):
        """Sets the service_tier of this ChatCompletion.


        :param service_tier: The service_tier of this ChatCompletion.  # noqa: E501
        :type: object
        """

        self._service_tier = service_tier

    @property
    def system_fingerprint(self):
        """Gets the system_fingerprint of this ChatCompletion.  # noqa: E501


        :return: The system_fingerprint of this ChatCompletion.  # noqa: E501
        :rtype: object
        """
        return self._system_fingerprint

    @system_fingerprint.setter
    def system_fingerprint(self, system_fingerprint):
        """Sets the system_fingerprint of this ChatCompletion.


        :param system_fingerprint: The system_fingerprint of this ChatCompletion.  # noqa: E501
        :type: object
        """

        self._system_fingerprint = system_fingerprint

    @property
    def usage(self):
        """Gets the usage of this ChatCompletion.  # noqa: E501


        :return: The usage of this ChatCompletion.  # noqa: E501
        :rtype: object
        """
        return self._usage

    @usage.setter
    def usage(self, usage):
        """Sets the usage of this ChatCompletion.


        :param usage: The usage of this ChatCompletion.  # noqa: E501
        :type: object
        """

        self._usage = usage

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ChatCompletion, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ChatCompletion):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
