# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ChatRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'content': 'object',
        'id': 'object',
        'agent_id': 'object',
        'agent_api_key': 'object',
        'graph_id': 'object',
        'llm_config_id': 'object',
        'system': 'object',
        'model': 'object',
        'streaming': 'object'
    }

    attribute_map = {
        'content': 'content',
        'id': 'id',
        'agent_id': 'agent_id',
        'agent_api_key': 'agent_api_key',
        'graph_id': 'graph_id',
        'llm_config_id': 'llm_config_id',
        'system': 'system',
        'model': 'model',
        'streaming': 'streaming'
    }

    def __init__(self, content=None, id=None, agent_id=None, agent_api_key=None, graph_id=None, llm_config_id=None, system=None, model=None, streaming=None):  # noqa: E501
        """ChatRequest - a model defined in Swagger"""  # noqa: E501
        self._content = None
        self._id = None
        self._agent_id = None
        self._agent_api_key = None
        self._graph_id = None
        self._llm_config_id = None
        self._system = None
        self._model = None
        self._streaming = None
        self.discriminator = None
        self.content = content
        if id is not None:
            self.id = id
        if agent_id is not None:
            self.agent_id = agent_id
        if agent_api_key is not None:
            self.agent_api_key = agent_api_key
        if graph_id is not None:
            self.graph_id = graph_id
        if llm_config_id is not None:
            self.llm_config_id = llm_config_id
        if system is not None:
            self.system = system
        if model is not None:
            self.model = model
        if streaming is not None:
            self.streaming = streaming

    @property
    def content(self):
        """Gets the content of this ChatRequest.  # noqa: E501


        :return: The content of this ChatRequest.  # noqa: E501
        :rtype: object
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this ChatRequest.


        :param content: The content of this ChatRequest.  # noqa: E501
        :type: object
        """
        if content is None:
            raise ValueError("Invalid value for `content`, must not be `None`")  # noqa: E501

        self._content = content

    @property
    def id(self):
        """Gets the id of this ChatRequest.  # noqa: E501


        :return: The id of this ChatRequest.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ChatRequest.


        :param id: The id of this ChatRequest.  # noqa: E501
        :type: object
        """

        self._id = id

    @property
    def agent_id(self):
        """Gets the agent_id of this ChatRequest.  # noqa: E501


        :return: The agent_id of this ChatRequest.  # noqa: E501
        :rtype: object
        """
        return self._agent_id

    @agent_id.setter
    def agent_id(self, agent_id):
        """Sets the agent_id of this ChatRequest.


        :param agent_id: The agent_id of this ChatRequest.  # noqa: E501
        :type: object
        """

        self._agent_id = agent_id

    @property
    def agent_api_key(self):
        """Gets the agent_api_key of this ChatRequest.  # noqa: E501


        :return: The agent_api_key of this ChatRequest.  # noqa: E501
        :rtype: object
        """
        return self._agent_api_key

    @agent_api_key.setter
    def agent_api_key(self, agent_api_key):
        """Sets the agent_api_key of this ChatRequest.


        :param agent_api_key: The agent_api_key of this ChatRequest.  # noqa: E501
        :type: object
        """

        self._agent_api_key = agent_api_key

    @property
    def graph_id(self):
        """Gets the graph_id of this ChatRequest.  # noqa: E501


        :return: The graph_id of this ChatRequest.  # noqa: E501
        :rtype: object
        """
        return self._graph_id

    @graph_id.setter
    def graph_id(self, graph_id):
        """Sets the graph_id of this ChatRequest.


        :param graph_id: The graph_id of this ChatRequest.  # noqa: E501
        :type: object
        """

        self._graph_id = graph_id

    @property
    def llm_config_id(self):
        """Gets the llm_config_id of this ChatRequest.  # noqa: E501


        :return: The llm_config_id of this ChatRequest.  # noqa: E501
        :rtype: object
        """
        return self._llm_config_id

    @llm_config_id.setter
    def llm_config_id(self, llm_config_id):
        """Sets the llm_config_id of this ChatRequest.


        :param llm_config_id: The llm_config_id of this ChatRequest.  # noqa: E501
        :type: object
        """

        self._llm_config_id = llm_config_id

    @property
    def system(self):
        """Gets the system of this ChatRequest.  # noqa: E501


        :return: The system of this ChatRequest.  # noqa: E501
        :rtype: object
        """
        return self._system

    @system.setter
    def system(self, system):
        """Sets the system of this ChatRequest.


        :param system: The system of this ChatRequest.  # noqa: E501
        :type: object
        """

        self._system = system

    @property
    def model(self):
        """Gets the model of this ChatRequest.  # noqa: E501


        :return: The model of this ChatRequest.  # noqa: E501
        :rtype: object
        """
        return self._model

    @model.setter
    def model(self, model):
        """Sets the model of this ChatRequest.


        :param model: The model of this ChatRequest.  # noqa: E501
        :type: object
        """

        self._model = model

    @property
    def streaming(self):
        """Gets the streaming of this ChatRequest.  # noqa: E501


        :return: The streaming of this ChatRequest.  # noqa: E501
        :rtype: object
        """
        return self._streaming

    @streaming.setter
    def streaming(self, streaming):
        """Sets the streaming of this ChatRequest.


        :param streaming: The streaming of this ChatRequest.  # noqa: E501
        :type: object
        """

        self._streaming = streaming

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ChatRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ChatRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
