# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ChatCompletionTokenLogprob(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'token': 'object',
        'bytes': 'object',
        'logprob': 'object',
        'top_logprobs': 'object'
    }

    attribute_map = {
        'token': 'token',
        'bytes': 'bytes',
        'logprob': 'logprob',
        'top_logprobs': 'top_logprobs'
    }

    def __init__(self, token=None, bytes=None, logprob=None, top_logprobs=None):  # noqa: E501
        """ChatCompletionTokenLogprob - a model defined in Swagger"""  # noqa: E501
        self._token = None
        self._bytes = None
        self._logprob = None
        self._top_logprobs = None
        self.discriminator = None
        self.token = token
        if bytes is not None:
            self.bytes = bytes
        self.logprob = logprob
        self.top_logprobs = top_logprobs

    @property
    def token(self):
        """Gets the token of this ChatCompletionTokenLogprob.  # noqa: E501


        :return: The token of this ChatCompletionTokenLogprob.  # noqa: E501
        :rtype: object
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this ChatCompletionTokenLogprob.


        :param token: The token of this ChatCompletionTokenLogprob.  # noqa: E501
        :type: object
        """
        if token is None:
            raise ValueError("Invalid value for `token`, must not be `None`")  # noqa: E501

        self._token = token

    @property
    def bytes(self):
        """Gets the bytes of this ChatCompletionTokenLogprob.  # noqa: E501


        :return: The bytes of this ChatCompletionTokenLogprob.  # noqa: E501
        :rtype: object
        """
        return self._bytes

    @bytes.setter
    def bytes(self, bytes):
        """Sets the bytes of this ChatCompletionTokenLogprob.


        :param bytes: The bytes of this ChatCompletionTokenLogprob.  # noqa: E501
        :type: object
        """

        self._bytes = bytes

    @property
    def logprob(self):
        """Gets the logprob of this ChatCompletionTokenLogprob.  # noqa: E501


        :return: The logprob of this ChatCompletionTokenLogprob.  # noqa: E501
        :rtype: object
        """
        return self._logprob

    @logprob.setter
    def logprob(self, logprob):
        """Sets the logprob of this ChatCompletionTokenLogprob.


        :param logprob: The logprob of this ChatCompletionTokenLogprob.  # noqa: E501
        :type: object
        """
        if logprob is None:
            raise ValueError("Invalid value for `logprob`, must not be `None`")  # noqa: E501

        self._logprob = logprob

    @property
    def top_logprobs(self):
        """Gets the top_logprobs of this ChatCompletionTokenLogprob.  # noqa: E501


        :return: The top_logprobs of this ChatCompletionTokenLogprob.  # noqa: E501
        :rtype: object
        """
        return self._top_logprobs

    @top_logprobs.setter
    def top_logprobs(self, top_logprobs):
        """Sets the top_logprobs of this ChatCompletionTokenLogprob.


        :param top_logprobs: The top_logprobs of this ChatCompletionTokenLogprob.  # noqa: E501
        :type: object
        """
        if top_logprobs is None:
            raise ValueError("Invalid value for `top_logprobs`, must not be `None`")  # noqa: E501

        self._top_logprobs = top_logprobs

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ChatCompletionTokenLogprob, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ChatCompletionTokenLogprob):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
