# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ChatCompletionMessageCustomToolCall(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'object',
        'custom': 'Custom',
        'type': 'object'
    }

    attribute_map = {
        'id': 'id',
        'custom': 'custom',
        'type': 'type'
    }

    def __init__(self, id=None, custom=None, type=None, *args, **kwargs):  # noqa: E501
        """ChatCompletionMessageCustomToolCall - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._custom = None
        self._type = None
        self.discriminator = None
        self.id = id
        self.custom = custom
        self.type = type

    @property
    def id(self):
        """Gets the id of this ChatCompletionMessageCustomToolCall.  # noqa: E501


        :return: The id of this ChatCompletionMessageCustomToolCall.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ChatCompletionMessageCustomToolCall.


        :param id: The id of this ChatCompletionMessageCustomToolCall.  # noqa: E501
        :type: object
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def custom(self):
        """Gets the custom of this ChatCompletionMessageCustomToolCall.  # noqa: E501


        :return: The custom of this ChatCompletionMessageCustomToolCall.  # noqa: E501
        :rtype: Custom
        """
        return self._custom

    @custom.setter
    def custom(self, custom):
        """Sets the custom of this ChatCompletionMessageCustomToolCall.


        :param custom: The custom of this ChatCompletionMessageCustomToolCall.  # noqa: E501
        :type: Custom
        """
        if custom is None:
            raise ValueError("Invalid value for `custom`, must not be `None`")  # noqa: E501

        self._custom = custom

    @property
    def type(self):
        """Gets the type of this ChatCompletionMessageCustomToolCall.  # noqa: E501


        :return: The type of this ChatCompletionMessageCustomToolCall.  # noqa: E501
        :rtype: object
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ChatCompletionMessageCustomToolCall.


        :param type: The type of this ChatCompletionMessageCustomToolCall.  # noqa: E501
        :type: object
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ChatCompletionMessageCustomToolCall, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ChatCompletionMessageCustomToolCall):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
