# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ChatCompletionRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'project_id': 'object',
        'messages': 'object',
        'agent_id': 'object',
        'agent_api_key': 'object',
        'graph_id': 'object',
        'group_id': 'object',
        'model': 'object',
        'reasoning_effort': 'object',
        'max_completion_tokens': 'object',
        'max_tokens': 'object',
        'top_p': 'object',
        'temperature': 'object',
        'frequency_penalty': 'object',
        'direct_citations': 'object',
        'citation_checking': 'object',
        'stream_response': 'object',
        'emit_graph_nodes': 'object'
    }

    attribute_map = {
        'project_id': 'project_id',
        'messages': 'messages',
        'agent_id': 'agent_id',
        'agent_api_key': 'agent_api_key',
        'graph_id': 'graph_id',
        'group_id': 'group_id',
        'model': 'model',
        'reasoning_effort': 'reasoning_effort',
        'max_completion_tokens': 'max_completion_tokens',
        'max_tokens': 'max_tokens',
        'top_p': 'top_p',
        'temperature': 'temperature',
        'frequency_penalty': 'frequency_penalty',
        'direct_citations': 'direct_citations',
        'citation_checking': 'citation_checking',
        'stream_response': 'stream_response',
        'emit_graph_nodes': 'emit_graph_nodes'
    }

    def __init__(self, project_id=None, messages=None, agent_id=None, agent_api_key=None, graph_id=None, group_id=None, model=None, reasoning_effort=None, max_completion_tokens=None, max_tokens=None, top_p=None, temperature=None, frequency_penalty=None, direct_citations=None, citation_checking=None, stream_response=None, emit_graph_nodes=None, *args, **kwargs):  # noqa: E501
        """ChatCompletionRequest - a model defined in Swagger"""  # noqa: E501
        self._project_id = None
        self._messages = None
        self._agent_id = None
        self._agent_api_key = None
        self._graph_id = None
        self._group_id = None
        self._model = None
        self._reasoning_effort = None
        self._max_completion_tokens = None
        self._max_tokens = None
        self._top_p = None
        self._temperature = None
        self._frequency_penalty = None
        self._direct_citations = None
        self._citation_checking = None
        self._stream_response = None
        self._emit_graph_nodes = None
        self.discriminator = None
        if project_id is not None:
            self.project_id = project_id
        self.messages = messages
        if agent_id is not None:
            self.agent_id = agent_id
        if agent_api_key is not None:
            self.agent_api_key = agent_api_key
        if graph_id is not None:
            self.graph_id = graph_id
        if group_id is not None:
            self.group_id = group_id
        if model is not None:
            self.model = model
        if reasoning_effort is not None:
            self.reasoning_effort = reasoning_effort
        if max_completion_tokens is not None:
            self.max_completion_tokens = max_completion_tokens
        if max_tokens is not None:
            self.max_tokens = max_tokens
        if top_p is not None:
            self.top_p = top_p
        if temperature is not None:
            self.temperature = temperature
        if frequency_penalty is not None:
            self.frequency_penalty = frequency_penalty
        if direct_citations is not None:
            self.direct_citations = direct_citations
        if citation_checking is not None:
            self.citation_checking = citation_checking
        if stream_response is not None:
            self.stream_response = stream_response
        if emit_graph_nodes is not None:
            self.emit_graph_nodes = emit_graph_nodes

    @property
    def project_id(self):
        """Gets the project_id of this ChatCompletionRequest.  # noqa: E501


        :return: The project_id of this ChatCompletionRequest.  # noqa: E501
        :rtype: object
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this ChatCompletionRequest.


        :param project_id: The project_id of this ChatCompletionRequest.  # noqa: E501
        :type: object
        """

        self._project_id = project_id

    @property
    def messages(self):
        """Gets the messages of this ChatCompletionRequest.  # noqa: E501


        :return: The messages of this ChatCompletionRequest.  # noqa: E501
        :rtype: object
        """
        return self._messages

    @messages.setter
    def messages(self, messages):
        """Sets the messages of this ChatCompletionRequest.


        :param messages: The messages of this ChatCompletionRequest.  # noqa: E501
        :type: object
        """
        if messages is None:
            raise ValueError("Invalid value for `messages`, must not be `None`")  # noqa: E501

        self._messages = messages

    @property
    def agent_id(self):
        """Gets the agent_id of this ChatCompletionRequest.  # noqa: E501


        :return: The agent_id of this ChatCompletionRequest.  # noqa: E501
        :rtype: object
        """
        return self._agent_id

    @agent_id.setter
    def agent_id(self, agent_id):
        """Sets the agent_id of this ChatCompletionRequest.


        :param agent_id: The agent_id of this ChatCompletionRequest.  # noqa: E501
        :type: object
        """

        self._agent_id = agent_id

    @property
    def agent_api_key(self):
        """Gets the agent_api_key of this ChatCompletionRequest.  # noqa: E501


        :return: The agent_api_key of this ChatCompletionRequest.  # noqa: E501
        :rtype: object
        """
        return self._agent_api_key

    @agent_api_key.setter
    def agent_api_key(self, agent_api_key):
        """Sets the agent_api_key of this ChatCompletionRequest.


        :param agent_api_key: The agent_api_key of this ChatCompletionRequest.  # noqa: E501
        :type: object
        """

        self._agent_api_key = agent_api_key

    @property
    def graph_id(self):
        """Gets the graph_id of this ChatCompletionRequest.  # noqa: E501


        :return: The graph_id of this ChatCompletionRequest.  # noqa: E501
        :rtype: object
        """
        return self._graph_id

    @graph_id.setter
    def graph_id(self, graph_id):
        """Sets the graph_id of this ChatCompletionRequest.


        :param graph_id: The graph_id of this ChatCompletionRequest.  # noqa: E501
        :type: object
        """

        self._graph_id = graph_id

    @property
    def group_id(self):
        """Gets the group_id of this ChatCompletionRequest.  # noqa: E501


        :return: The group_id of this ChatCompletionRequest.  # noqa: E501
        :rtype: object
        """
        return self._group_id

    @group_id.setter
    def group_id(self, group_id):
        """Sets the group_id of this ChatCompletionRequest.


        :param group_id: The group_id of this ChatCompletionRequest.  # noqa: E501
        :type: object
        """

        self._group_id = group_id

    @property
    def model(self):
        """Gets the model of this ChatCompletionRequest.  # noqa: E501


        :return: The model of this ChatCompletionRequest.  # noqa: E501
        :rtype: object
        """
        return self._model

    @model.setter
    def model(self, model):
        """Sets the model of this ChatCompletionRequest.


        :param model: The model of this ChatCompletionRequest.  # noqa: E501
        :type: object
        """

        self._model = model

    @property
    def reasoning_effort(self):
        """Gets the reasoning_effort of this ChatCompletionRequest.  # noqa: E501


        :return: The reasoning_effort of this ChatCompletionRequest.  # noqa: E501
        :rtype: object
        """
        return self._reasoning_effort

    @reasoning_effort.setter
    def reasoning_effort(self, reasoning_effort):
        """Sets the reasoning_effort of this ChatCompletionRequest.


        :param reasoning_effort: The reasoning_effort of this ChatCompletionRequest.  # noqa: E501
        :type: object
        """

        self._reasoning_effort = reasoning_effort

    @property
    def max_completion_tokens(self):
        """Gets the max_completion_tokens of this ChatCompletionRequest.  # noqa: E501


        :return: The max_completion_tokens of this ChatCompletionRequest.  # noqa: E501
        :rtype: object
        """
        return self._max_completion_tokens

    @max_completion_tokens.setter
    def max_completion_tokens(self, max_completion_tokens):
        """Sets the max_completion_tokens of this ChatCompletionRequest.


        :param max_completion_tokens: The max_completion_tokens of this ChatCompletionRequest.  # noqa: E501
        :type: object
        """

        self._max_completion_tokens = max_completion_tokens

    @property
    def max_tokens(self):
        """Gets the max_tokens of this ChatCompletionRequest.  # noqa: E501


        :return: The max_tokens of this ChatCompletionRequest.  # noqa: E501
        :rtype: object
        """
        return self._max_tokens

    @max_tokens.setter
    def max_tokens(self, max_tokens):
        """Sets the max_tokens of this ChatCompletionRequest.


        :param max_tokens: The max_tokens of this ChatCompletionRequest.  # noqa: E501
        :type: object
        """

        self._max_tokens = max_tokens

    @property
    def top_p(self):
        """Gets the top_p of this ChatCompletionRequest.  # noqa: E501


        :return: The top_p of this ChatCompletionRequest.  # noqa: E501
        :rtype: object
        """
        return self._top_p

    @top_p.setter
    def top_p(self, top_p):
        """Sets the top_p of this ChatCompletionRequest.


        :param top_p: The top_p of this ChatCompletionRequest.  # noqa: E501
        :type: object
        """

        self._top_p = top_p

    @property
    def temperature(self):
        """Gets the temperature of this ChatCompletionRequest.  # noqa: E501


        :return: The temperature of this ChatCompletionRequest.  # noqa: E501
        :rtype: object
        """
        return self._temperature

    @temperature.setter
    def temperature(self, temperature):
        """Sets the temperature of this ChatCompletionRequest.


        :param temperature: The temperature of this ChatCompletionRequest.  # noqa: E501
        :type: object
        """

        self._temperature = temperature

    @property
    def frequency_penalty(self):
        """Gets the frequency_penalty of this ChatCompletionRequest.  # noqa: E501


        :return: The frequency_penalty of this ChatCompletionRequest.  # noqa: E501
        :rtype: object
        """
        return self._frequency_penalty

    @frequency_penalty.setter
    def frequency_penalty(self, frequency_penalty):
        """Sets the frequency_penalty of this ChatCompletionRequest.


        :param frequency_penalty: The frequency_penalty of this ChatCompletionRequest.  # noqa: E501
        :type: object
        """

        self._frequency_penalty = frequency_penalty

    @property
    def direct_citations(self):
        """Gets the direct_citations of this ChatCompletionRequest.  # noqa: E501


        :return: The direct_citations of this ChatCompletionRequest.  # noqa: E501
        :rtype: object
        """
        return self._direct_citations

    @direct_citations.setter
    def direct_citations(self, direct_citations):
        """Sets the direct_citations of this ChatCompletionRequest.


        :param direct_citations: The direct_citations of this ChatCompletionRequest.  # noqa: E501
        :type: object
        """

        self._direct_citations = direct_citations

    @property
    def citation_checking(self):
        """Gets the citation_checking of this ChatCompletionRequest.  # noqa: E501


        :return: The citation_checking of this ChatCompletionRequest.  # noqa: E501
        :rtype: object
        """
        return self._citation_checking

    @citation_checking.setter
    def citation_checking(self, citation_checking):
        """Sets the citation_checking of this ChatCompletionRequest.


        :param citation_checking: The citation_checking of this ChatCompletionRequest.  # noqa: E501
        :type: object
        """

        self._citation_checking = citation_checking

    @property
    def stream_response(self):
        """Gets the stream_response of this ChatCompletionRequest.  # noqa: E501


        :return: The stream_response of this ChatCompletionRequest.  # noqa: E501
        :rtype: object
        """
        return self._stream_response

    @stream_response.setter
    def stream_response(self, stream_response):
        """Sets the stream_response of this ChatCompletionRequest.


        :param stream_response: The stream_response of this ChatCompletionRequest.  # noqa: E501
        :type: object
        """

        self._stream_response = stream_response

    @property
    def emit_graph_nodes(self):
        """Gets the emit_graph_nodes of this ChatCompletionRequest.  # noqa: E501


        :return: The emit_graph_nodes of this ChatCompletionRequest.  # noqa: E501
        :rtype: object
        """
        return self._emit_graph_nodes

    @emit_graph_nodes.setter
    def emit_graph_nodes(self, emit_graph_nodes):
        """Sets the emit_graph_nodes of this ChatCompletionRequest.


        :param emit_graph_nodes: The emit_graph_nodes of this ChatCompletionRequest.  # noqa: E501
        :type: object
        """

        self._emit_graph_nodes = emit_graph_nodes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ChatCompletionRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ChatCompletionRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
