# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ChatResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'object',
        'conversation_name': 'object',
        'resolution': 'object',
        'process': 'object'
    }

    attribute_map = {
        'id': 'id',
        'conversation_name': 'conversation_name',
        'resolution': 'resolution',
        'process': 'process'
    }

    def __init__(self, id=None, conversation_name=None, resolution=None, process=None):  # noqa: E501
        """ChatResponse - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._conversation_name = None
        self._resolution = None
        self._process = None
        self.discriminator = None
        if id is not None:
            self.id = id
        self.conversation_name = conversation_name
        self.resolution = resolution
        self.process = process

    @property
    def id(self):
        """Gets the id of this ChatResponse.  # noqa: E501


        :return: The id of this ChatResponse.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ChatResponse.


        :param id: The id of this ChatResponse.  # noqa: E501
        :type: object
        """

        self._id = id

    @property
    def conversation_name(self):
        """Gets the conversation_name of this ChatResponse.  # noqa: E501


        :return: The conversation_name of this ChatResponse.  # noqa: E501
        :rtype: object
        """
        return self._conversation_name

    @conversation_name.setter
    def conversation_name(self, conversation_name):
        """Sets the conversation_name of this ChatResponse.


        :param conversation_name: The conversation_name of this ChatResponse.  # noqa: E501
        :type: object
        """
        if conversation_name is None:
            raise ValueError("Invalid value for `conversation_name`, must not be `None`")  # noqa: E501

        self._conversation_name = conversation_name

    @property
    def resolution(self):
        """Gets the resolution of this ChatResponse.  # noqa: E501


        :return: The resolution of this ChatResponse.  # noqa: E501
        :rtype: object
        """
        return self._resolution

    @resolution.setter
    def resolution(self, resolution):
        """Sets the resolution of this ChatResponse.


        :param resolution: The resolution of this ChatResponse.  # noqa: E501
        :type: object
        """
        if resolution is None:
            raise ValueError("Invalid value for `resolution`, must not be `None`")  # noqa: E501

        self._resolution = resolution

    @property
    def process(self):
        """Gets the process of this ChatResponse.  # noqa: E501


        :return: The process of this ChatResponse.  # noqa: E501
        :rtype: object
        """
        return self._process

    @process.setter
    def process(self, process):
        """Sets the process of this ChatResponse.


        :param process: The process of this ChatResponse.  # noqa: E501
        :type: object
        """
        if process is None:
            raise ValueError("Invalid value for `process`, must not be `None`")  # noqa: E501

        self._process = process

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ChatResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ChatResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
