# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Choice(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'finish_reason': 'object',
        'index': 'object',
        'logprobs': 'object',
        'message': 'ChatCompletionMessage'
    }

    attribute_map = {
        'finish_reason': 'finish_reason',
        'index': 'index',
        'logprobs': 'logprobs',
        'message': 'message'
    }

    def __init__(self, finish_reason=None, index=None, logprobs=None, message=None):  # noqa: E501
        """Choice - a model defined in Swagger"""  # noqa: E501
        self._finish_reason = None
        self._index = None
        self._logprobs = None
        self._message = None
        self.discriminator = None
        self.finish_reason = finish_reason
        self.index = index
        if logprobs is not None:
            self.logprobs = logprobs
        self.message = message

    @property
    def finish_reason(self):
        """Gets the finish_reason of this Choice.  # noqa: E501


        :return: The finish_reason of this Choice.  # noqa: E501
        :rtype: object
        """
        return self._finish_reason

    @finish_reason.setter
    def finish_reason(self, finish_reason):
        """Sets the finish_reason of this Choice.


        :param finish_reason: The finish_reason of this Choice.  # noqa: E501
        :type: object
        """
        if finish_reason is None:
            raise ValueError("Invalid value for `finish_reason`, must not be `None`")  # noqa: E501

        self._finish_reason = finish_reason

    @property
    def index(self):
        """Gets the index of this Choice.  # noqa: E501


        :return: The index of this Choice.  # noqa: E501
        :rtype: object
        """
        return self._index

    @index.setter
    def index(self, index):
        """Sets the index of this Choice.


        :param index: The index of this Choice.  # noqa: E501
        :type: object
        """
        if index is None:
            raise ValueError("Invalid value for `index`, must not be `None`")  # noqa: E501

        self._index = index

    @property
    def logprobs(self):
        """Gets the logprobs of this Choice.  # noqa: E501


        :return: The logprobs of this Choice.  # noqa: E501
        :rtype: object
        """
        return self._logprobs

    @logprobs.setter
    def logprobs(self, logprobs):
        """Sets the logprobs of this Choice.


        :param logprobs: The logprobs of this Choice.  # noqa: E501
        :type: object
        """

        self._logprobs = logprobs

    @property
    def message(self):
        """Gets the message of this Choice.  # noqa: E501


        :return: The message of this Choice.  # noqa: E501
        :rtype: ChatCompletionMessage
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this Choice.


        :param message: The message of this Choice.  # noqa: E501
        :type: ChatCompletionMessage
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Choice, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Choice):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
