# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ChoiceLogprobs(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'content': 'object',
        'refusal': 'object'
    }

    attribute_map = {
        'content': 'content',
        'refusal': 'refusal'
    }

    def __init__(self, content=None, refusal=None):  # noqa: E501
        """ChoiceLogprobs - a model defined in Swagger"""  # noqa: E501
        self._content = None
        self._refusal = None
        self.discriminator = None
        if content is not None:
            self.content = content
        if refusal is not None:
            self.refusal = refusal

    @property
    def content(self):
        """Gets the content of this ChoiceLogprobs.  # noqa: E501


        :return: The content of this ChoiceLogprobs.  # noqa: E501
        :rtype: object
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this ChoiceLogprobs.


        :param content: The content of this ChoiceLogprobs.  # noqa: E501
        :type: object
        """

        self._content = content

    @property
    def refusal(self):
        """Gets the refusal of this ChoiceLogprobs.  # noqa: E501


        :return: The refusal of this ChoiceLogprobs.  # noqa: E501
        :rtype: object
        """
        return self._refusal

    @refusal.setter
    def refusal(self, refusal):
        """Sets the refusal of this ChoiceLogprobs.


        :param refusal: The refusal of this ChoiceLogprobs.  # noqa: E501
        :type: object
        """

        self._refusal = refusal

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ChoiceLogprobs, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ChoiceLogprobs):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
