# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CompletionUsage(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'completion_tokens': 'object',
        'prompt_tokens': 'object',
        'total_tokens': 'object',
        'completion_tokens_details': 'object',
        'prompt_tokens_details': 'object'
    }

    attribute_map = {
        'completion_tokens': 'completion_tokens',
        'prompt_tokens': 'prompt_tokens',
        'total_tokens': 'total_tokens',
        'completion_tokens_details': 'completion_tokens_details',
        'prompt_tokens_details': 'prompt_tokens_details'
    }

    def __init__(self, completion_tokens=None, prompt_tokens=None, total_tokens=None, completion_tokens_details=None, prompt_tokens_details=None):  # noqa: E501
        """CompletionUsage - a model defined in Swagger"""  # noqa: E501
        self._completion_tokens = None
        self._prompt_tokens = None
        self._total_tokens = None
        self._completion_tokens_details = None
        self._prompt_tokens_details = None
        self.discriminator = None
        self.completion_tokens = completion_tokens
        self.prompt_tokens = prompt_tokens
        self.total_tokens = total_tokens
        if completion_tokens_details is not None:
            self.completion_tokens_details = completion_tokens_details
        if prompt_tokens_details is not None:
            self.prompt_tokens_details = prompt_tokens_details

    @property
    def completion_tokens(self):
        """Gets the completion_tokens of this CompletionUsage.  # noqa: E501


        :return: The completion_tokens of this CompletionUsage.  # noqa: E501
        :rtype: object
        """
        return self._completion_tokens

    @completion_tokens.setter
    def completion_tokens(self, completion_tokens):
        """Sets the completion_tokens of this CompletionUsage.


        :param completion_tokens: The completion_tokens of this CompletionUsage.  # noqa: E501
        :type: object
        """
        if completion_tokens is None:
            raise ValueError("Invalid value for `completion_tokens`, must not be `None`")  # noqa: E501

        self._completion_tokens = completion_tokens

    @property
    def prompt_tokens(self):
        """Gets the prompt_tokens of this CompletionUsage.  # noqa: E501


        :return: The prompt_tokens of this CompletionUsage.  # noqa: E501
        :rtype: object
        """
        return self._prompt_tokens

    @prompt_tokens.setter
    def prompt_tokens(self, prompt_tokens):
        """Sets the prompt_tokens of this CompletionUsage.


        :param prompt_tokens: The prompt_tokens of this CompletionUsage.  # noqa: E501
        :type: object
        """
        if prompt_tokens is None:
            raise ValueError("Invalid value for `prompt_tokens`, must not be `None`")  # noqa: E501

        self._prompt_tokens = prompt_tokens

    @property
    def total_tokens(self):
        """Gets the total_tokens of this CompletionUsage.  # noqa: E501


        :return: The total_tokens of this CompletionUsage.  # noqa: E501
        :rtype: object
        """
        return self._total_tokens

    @total_tokens.setter
    def total_tokens(self, total_tokens):
        """Sets the total_tokens of this CompletionUsage.


        :param total_tokens: The total_tokens of this CompletionUsage.  # noqa: E501
        :type: object
        """
        if total_tokens is None:
            raise ValueError("Invalid value for `total_tokens`, must not be `None`")  # noqa: E501

        self._total_tokens = total_tokens

    @property
    def completion_tokens_details(self):
        """Gets the completion_tokens_details of this CompletionUsage.  # noqa: E501


        :return: The completion_tokens_details of this CompletionUsage.  # noqa: E501
        :rtype: object
        """
        return self._completion_tokens_details

    @completion_tokens_details.setter
    def completion_tokens_details(self, completion_tokens_details):
        """Sets the completion_tokens_details of this CompletionUsage.


        :param completion_tokens_details: The completion_tokens_details of this CompletionUsage.  # noqa: E501
        :type: object
        """

        self._completion_tokens_details = completion_tokens_details

    @property
    def prompt_tokens_details(self):
        """Gets the prompt_tokens_details of this CompletionUsage.  # noqa: E501


        :return: The prompt_tokens_details of this CompletionUsage.  # noqa: E501
        :rtype: object
        """
        return self._prompt_tokens_details

    @prompt_tokens_details.setter
    def prompt_tokens_details(self, prompt_tokens_details):
        """Sets the prompt_tokens_details of this CompletionUsage.


        :param prompt_tokens_details: The prompt_tokens_details of this CompletionUsage.  # noqa: E501
        :type: object
        """

        self._prompt_tokens_details = prompt_tokens_details

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CompletionUsage, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CompletionUsage):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
