# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConnectionConfigRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'object',
        'schema': 'object',
        'connection_parameters': 'ConnectionParams',
        'llm_config_id': 'object'
    }

    attribute_map = {
        'name': 'name',
        'schema': 'schema',
        'connection_parameters': 'connection_parameters',
        'llm_config_id': 'llm_config_id'
    }

    def __init__(self, name=None, schema=None, connection_parameters=None, llm_config_id=None):  # noqa: E501
        """ConnectionConfigRequest - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._schema = None
        self._connection_parameters = None
        self._llm_config_id = None
        self.discriminator = None
        self.name = name
        self.schema = schema
        self.connection_parameters = connection_parameters
        if llm_config_id is not None:
            self.llm_config_id = llm_config_id

    @property
    def name(self):
        """Gets the name of this ConnectionConfigRequest.  # noqa: E501


        :return: The name of this ConnectionConfigRequest.  # noqa: E501
        :rtype: object
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ConnectionConfigRequest.


        :param name: The name of this ConnectionConfigRequest.  # noqa: E501
        :type: object
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def schema(self):
        """Gets the schema of this ConnectionConfigRequest.  # noqa: E501


        :return: The schema of this ConnectionConfigRequest.  # noqa: E501
        :rtype: object
        """
        return self._schema

    @schema.setter
    def schema(self, schema):
        """Sets the schema of this ConnectionConfigRequest.


        :param schema: The schema of this ConnectionConfigRequest.  # noqa: E501
        :type: object
        """
        if schema is None:
            raise ValueError("Invalid value for `schema`, must not be `None`")  # noqa: E501

        self._schema = schema

    @property
    def connection_parameters(self):
        """Gets the connection_parameters of this ConnectionConfigRequest.  # noqa: E501


        :return: The connection_parameters of this ConnectionConfigRequest.  # noqa: E501
        :rtype: ConnectionParams
        """
        return self._connection_parameters

    @connection_parameters.setter
    def connection_parameters(self, connection_parameters):
        """Sets the connection_parameters of this ConnectionConfigRequest.


        :param connection_parameters: The connection_parameters of this ConnectionConfigRequest.  # noqa: E501
        :type: ConnectionParams
        """
        if connection_parameters is None:
            raise ValueError("Invalid value for `connection_parameters`, must not be `None`")  # noqa: E501

        self._connection_parameters = connection_parameters

    @property
    def llm_config_id(self):
        """Gets the llm_config_id of this ConnectionConfigRequest.  # noqa: E501


        :return: The llm_config_id of this ConnectionConfigRequest.  # noqa: E501
        :rtype: object
        """
        return self._llm_config_id

    @llm_config_id.setter
    def llm_config_id(self, llm_config_id):
        """Sets the llm_config_id of this ConnectionConfigRequest.


        :param llm_config_id: The llm_config_id of this ConnectionConfigRequest.  # noqa: E501
        :type: object
        """

        self._llm_config_id = llm_config_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConnectionConfigRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConnectionConfigRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
