# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConnectionConfigObject(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'conn_schema': 'object',
        'name': 'object',
        'hostname_path': 'object',
        'graph_id': 'object',
        'id': 'object',
        'username': 'object',
        'password': 'object',
        'port': 'object',
        'database': 'object',
        'parameters': 'object',
        'account': 'object',
        'warehouse': 'object',
        'role': 'object',
        'sf_schema': 'object'
    }

    attribute_map = {
        'conn_schema': 'conn_schema',
        'name': 'name',
        'hostname_path': 'hostname_path',
        'graph_id': 'graph_id',
        'id': 'id',
        'username': 'username',
        'password': 'password',
        'port': 'port',
        'database': 'database',
        'parameters': 'parameters',
        'account': 'account',
        'warehouse': 'warehouse',
        'role': 'role',
        'sf_schema': 'sf_schema'
    }

    def __init__(self, conn_schema=None, name=None, hostname_path=None, graph_id=None, id=None, username=None, password=None, port=None, database=None, parameters=None, account=None, warehouse=None, role=None, sf_schema=None):  # noqa: E501
        """ConnectionConfigObject - a model defined in Swagger"""  # noqa: E501
        self._conn_schema = None
        self._name = None
        self._hostname_path = None
        self._graph_id = None
        self._id = None
        self._username = None
        self._password = None
        self._port = None
        self._database = None
        self._parameters = None
        self._account = None
        self._warehouse = None
        self._role = None
        self._sf_schema = None
        self.discriminator = None
        self.conn_schema = conn_schema
        if name is not None:
            self.name = name
        if hostname_path is not None:
            self.hostname_path = hostname_path
        if graph_id is not None:
            self.graph_id = graph_id
        if id is not None:
            self.id = id
        if username is not None:
            self.username = username
        if password is not None:
            self.password = password
        if port is not None:
            self.port = port
        if database is not None:
            self.database = database
        if parameters is not None:
            self.parameters = parameters
        if account is not None:
            self.account = account
        if warehouse is not None:
            self.warehouse = warehouse
        if role is not None:
            self.role = role
        if sf_schema is not None:
            self.sf_schema = sf_schema

    @property
    def conn_schema(self):
        """Gets the conn_schema of this ConnectionConfigObject.  # noqa: E501


        :return: The conn_schema of this ConnectionConfigObject.  # noqa: E501
        :rtype: object
        """
        return self._conn_schema

    @conn_schema.setter
    def conn_schema(self, conn_schema):
        """Sets the conn_schema of this ConnectionConfigObject.


        :param conn_schema: The conn_schema of this ConnectionConfigObject.  # noqa: E501
        :type: object
        """
        if conn_schema is None:
            raise ValueError("Invalid value for `conn_schema`, must not be `None`")  # noqa: E501

        self._conn_schema = conn_schema

    @property
    def name(self):
        """Gets the name of this ConnectionConfigObject.  # noqa: E501


        :return: The name of this ConnectionConfigObject.  # noqa: E501
        :rtype: object
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ConnectionConfigObject.


        :param name: The name of this ConnectionConfigObject.  # noqa: E501
        :type: object
        """

        self._name = name

    @property
    def hostname_path(self):
        """Gets the hostname_path of this ConnectionConfigObject.  # noqa: E501


        :return: The hostname_path of this ConnectionConfigObject.  # noqa: E501
        :rtype: object
        """
        return self._hostname_path

    @hostname_path.setter
    def hostname_path(self, hostname_path):
        """Sets the hostname_path of this ConnectionConfigObject.


        :param hostname_path: The hostname_path of this ConnectionConfigObject.  # noqa: E501
        :type: object
        """

        self._hostname_path = hostname_path

    @property
    def graph_id(self):
        """Gets the graph_id of this ConnectionConfigObject.  # noqa: E501


        :return: The graph_id of this ConnectionConfigObject.  # noqa: E501
        :rtype: object
        """
        return self._graph_id

    @graph_id.setter
    def graph_id(self, graph_id):
        """Sets the graph_id of this ConnectionConfigObject.


        :param graph_id: The graph_id of this ConnectionConfigObject.  # noqa: E501
        :type: object
        """

        self._graph_id = graph_id

    @property
    def id(self):
        """Gets the id of this ConnectionConfigObject.  # noqa: E501


        :return: The id of this ConnectionConfigObject.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ConnectionConfigObject.


        :param id: The id of this ConnectionConfigObject.  # noqa: E501
        :type: object
        """

        self._id = id

    @property
    def username(self):
        """Gets the username of this ConnectionConfigObject.  # noqa: E501


        :return: The username of this ConnectionConfigObject.  # noqa: E501
        :rtype: object
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this ConnectionConfigObject.


        :param username: The username of this ConnectionConfigObject.  # noqa: E501
        :type: object
        """

        self._username = username

    @property
    def password(self):
        """Gets the password of this ConnectionConfigObject.  # noqa: E501


        :return: The password of this ConnectionConfigObject.  # noqa: E501
        :rtype: object
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this ConnectionConfigObject.


        :param password: The password of this ConnectionConfigObject.  # noqa: E501
        :type: object
        """

        self._password = password

    @property
    def port(self):
        """Gets the port of this ConnectionConfigObject.  # noqa: E501


        :return: The port of this ConnectionConfigObject.  # noqa: E501
        :rtype: object
        """
        return self._port

    @port.setter
    def port(self, port):
        """Sets the port of this ConnectionConfigObject.


        :param port: The port of this ConnectionConfigObject.  # noqa: E501
        :type: object
        """

        self._port = port

    @property
    def database(self):
        """Gets the database of this ConnectionConfigObject.  # noqa: E501


        :return: The database of this ConnectionConfigObject.  # noqa: E501
        :rtype: object
        """
        return self._database

    @database.setter
    def database(self, database):
        """Sets the database of this ConnectionConfigObject.


        :param database: The database of this ConnectionConfigObject.  # noqa: E501
        :type: object
        """

        self._database = database

    @property
    def parameters(self):
        """Gets the parameters of this ConnectionConfigObject.  # noqa: E501


        :return: The parameters of this ConnectionConfigObject.  # noqa: E501
        :rtype: object
        """
        return self._parameters

    @parameters.setter
    def parameters(self, parameters):
        """Sets the parameters of this ConnectionConfigObject.


        :param parameters: The parameters of this ConnectionConfigObject.  # noqa: E501
        :type: object
        """

        self._parameters = parameters

    @property
    def account(self):
        """Gets the account of this ConnectionConfigObject.  # noqa: E501


        :return: The account of this ConnectionConfigObject.  # noqa: E501
        :rtype: object
        """
        return self._account

    @account.setter
    def account(self, account):
        """Sets the account of this ConnectionConfigObject.


        :param account: The account of this ConnectionConfigObject.  # noqa: E501
        :type: object
        """

        self._account = account

    @property
    def warehouse(self):
        """Gets the warehouse of this ConnectionConfigObject.  # noqa: E501


        :return: The warehouse of this ConnectionConfigObject.  # noqa: E501
        :rtype: object
        """
        return self._warehouse

    @warehouse.setter
    def warehouse(self, warehouse):
        """Sets the warehouse of this ConnectionConfigObject.


        :param warehouse: The warehouse of this ConnectionConfigObject.  # noqa: E501
        :type: object
        """

        self._warehouse = warehouse

    @property
    def role(self):
        """Gets the role of this ConnectionConfigObject.  # noqa: E501


        :return: The role of this ConnectionConfigObject.  # noqa: E501
        :rtype: object
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this ConnectionConfigObject.


        :param role: The role of this ConnectionConfigObject.  # noqa: E501
        :type: object
        """

        self._role = role

    @property
    def sf_schema(self):
        """Gets the sf_schema of this ConnectionConfigObject.  # noqa: E501


        :return: The sf_schema of this ConnectionConfigObject.  # noqa: E501
        :rtype: object
        """
        return self._sf_schema

    @sf_schema.setter
    def sf_schema(self, sf_schema):
        """Sets the sf_schema of this ConnectionConfigObject.


        :param sf_schema: The sf_schema of this ConnectionConfigObject.  # noqa: E501
        :type: object
        """

        self._sf_schema = sf_schema

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConnectionConfigObject, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConnectionConfigObject):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
