# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConnectionParams(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'hostname_path': 'object',
        'conn_schema': 'object',
        'username': 'object',
        'password': 'object',
        'port': 'object',
        'database': 'object',
        'parameters': 'object'
    }

    attribute_map = {
        'hostname_path': 'hostname_path',
        'conn_schema': 'conn_schema',
        'username': 'username',
        'password': 'password',
        'port': 'port',
        'database': 'database',
        'parameters': 'parameters'
    }

    def __init__(self, hostname_path=None, conn_schema=None, username=None, password=None, port=None, database=None, parameters=None):  # noqa: E501
        """ConnectionParams - a model defined in Swagger"""  # noqa: E501
        self._hostname_path = None
        self._conn_schema = None
        self._username = None
        self._password = None
        self._port = None
        self._database = None
        self._parameters = None
        self.discriminator = None
        self.hostname_path = hostname_path
        self.conn_schema = conn_schema
        if username is not None:
            self.username = username
        if password is not None:
            self.password = password
        if port is not None:
            self.port = port
        if database is not None:
            self.database = database
        if parameters is not None:
            self.parameters = parameters

    @property
    def hostname_path(self):
        """Gets the hostname_path of this ConnectionParams.  # noqa: E501


        :return: The hostname_path of this ConnectionParams.  # noqa: E501
        :rtype: object
        """
        return self._hostname_path

    @hostname_path.setter
    def hostname_path(self, hostname_path):
        """Sets the hostname_path of this ConnectionParams.


        :param hostname_path: The hostname_path of this ConnectionParams.  # noqa: E501
        :type: object
        """
        if hostname_path is None:
            raise ValueError("Invalid value for `hostname_path`, must not be `None`")  # noqa: E501

        self._hostname_path = hostname_path

    @property
    def conn_schema(self):
        """Gets the conn_schema of this ConnectionParams.  # noqa: E501


        :return: The conn_schema of this ConnectionParams.  # noqa: E501
        :rtype: object
        """
        return self._conn_schema

    @conn_schema.setter
    def conn_schema(self, conn_schema):
        """Sets the conn_schema of this ConnectionParams.


        :param conn_schema: The conn_schema of this ConnectionParams.  # noqa: E501
        :type: object
        """
        if conn_schema is None:
            raise ValueError("Invalid value for `conn_schema`, must not be `None`")  # noqa: E501

        self._conn_schema = conn_schema

    @property
    def username(self):
        """Gets the username of this ConnectionParams.  # noqa: E501


        :return: The username of this ConnectionParams.  # noqa: E501
        :rtype: object
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this ConnectionParams.


        :param username: The username of this ConnectionParams.  # noqa: E501
        :type: object
        """

        self._username = username

    @property
    def password(self):
        """Gets the password of this ConnectionParams.  # noqa: E501


        :return: The password of this ConnectionParams.  # noqa: E501
        :rtype: object
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this ConnectionParams.


        :param password: The password of this ConnectionParams.  # noqa: E501
        :type: object
        """

        self._password = password

    @property
    def port(self):
        """Gets the port of this ConnectionParams.  # noqa: E501


        :return: The port of this ConnectionParams.  # noqa: E501
        :rtype: object
        """
        return self._port

    @port.setter
    def port(self, port):
        """Sets the port of this ConnectionParams.


        :param port: The port of this ConnectionParams.  # noqa: E501
        :type: object
        """

        self._port = port

    @property
    def database(self):
        """Gets the database of this ConnectionParams.  # noqa: E501


        :return: The database of this ConnectionParams.  # noqa: E501
        :rtype: object
        """
        return self._database

    @database.setter
    def database(self, database):
        """Sets the database of this ConnectionParams.


        :param database: The database of this ConnectionParams.  # noqa: E501
        :type: object
        """

        self._database = database

    @property
    def parameters(self):
        """Gets the parameters of this ConnectionParams.  # noqa: E501


        :return: The parameters of this ConnectionParams.  # noqa: E501
        :rtype: object
        """
        return self._parameters

    @parameters.setter
    def parameters(self, parameters):
        """Sets the parameters of this ConnectionParams.


        :param parameters: The parameters of this ConnectionParams.  # noqa: E501
        :type: object
        """

        self._parameters = parameters

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConnectionParams, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConnectionParams):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
