# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DataContextAPITokens(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'primary': 'object',
        'secondary': 'object'
    }

    attribute_map = {
        'primary': 'primary',
        'secondary': 'secondary'
    }

    def __init__(self, primary=None, secondary=None, *args, **kwargs):  # noqa: E501
        """DataContextAPITokens - a model defined in Swagger"""  # noqa: E501
        self._primary = None
        self._secondary = None
        self.discriminator = None
        if primary is not None:
            self.primary = primary
        if secondary is not None:
            self.secondary = secondary

    @property
    def primary(self):
        """Gets the primary of this DataContextAPITokens.  # noqa: E501


        :return: The primary of this DataContextAPITokens.  # noqa: E501
        :rtype: object
        """
        return self._primary

    @primary.setter
    def primary(self, primary):
        """Sets the primary of this DataContextAPITokens.


        :param primary: The primary of this DataContextAPITokens.  # noqa: E501
        :type: object
        """

        self._primary = primary

    @property
    def secondary(self):
        """Gets the secondary of this DataContextAPITokens.  # noqa: E501


        :return: The secondary of this DataContextAPITokens.  # noqa: E501
        :rtype: object
        """
        return self._secondary

    @secondary.setter
    def secondary(self, secondary):
        """Sets the secondary of this DataContextAPITokens.


        :param secondary: The secondary of this DataContextAPITokens.  # noqa: E501
        :type: object
        """

        self._secondary = secondary

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DataContextAPITokens, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DataContextAPITokens):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
