# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DataContextObject(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'object',
        'status': 'object',
        'id': 'object',
        'llm_config_id': 'object',
        'error_message': 'object',
        'config_ids': 'object',
        'conn_schemas': 'object'
    }

    attribute_map = {
        'name': 'name',
        'status': 'status',
        'id': 'id',
        'llm_config_id': 'llm_config_id',
        'error_message': 'error_message',
        'config_ids': 'config_ids',
        'conn_schemas': 'conn_schemas'
    }

    def __init__(self, name=None, status=None, id=None, llm_config_id=None, error_message=None, config_ids=None, conn_schemas=None):  # noqa: E501
        """DataContextObject - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._status = None
        self._id = None
        self._llm_config_id = None
        self._error_message = None
        self._config_ids = None
        self._conn_schemas = None
        self.discriminator = None
        self.name = name
        self.status = status
        if id is not None:
            self.id = id
        if llm_config_id is not None:
            self.llm_config_id = llm_config_id
        if error_message is not None:
            self.error_message = error_message
        if config_ids is not None:
            self.config_ids = config_ids
        if conn_schemas is not None:
            self.conn_schemas = conn_schemas

    @property
    def name(self):
        """Gets the name of this DataContextObject.  # noqa: E501


        :return: The name of this DataContextObject.  # noqa: E501
        :rtype: object
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this DataContextObject.


        :param name: The name of this DataContextObject.  # noqa: E501
        :type: object
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def status(self):
        """Gets the status of this DataContextObject.  # noqa: E501


        :return: The status of this DataContextObject.  # noqa: E501
        :rtype: object
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this DataContextObject.


        :param status: The status of this DataContextObject.  # noqa: E501
        :type: object
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def id(self):
        """Gets the id of this DataContextObject.  # noqa: E501


        :return: The id of this DataContextObject.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this DataContextObject.


        :param id: The id of this DataContextObject.  # noqa: E501
        :type: object
        """

        self._id = id

    @property
    def llm_config_id(self):
        """Gets the llm_config_id of this DataContextObject.  # noqa: E501


        :return: The llm_config_id of this DataContextObject.  # noqa: E501
        :rtype: object
        """
        return self._llm_config_id

    @llm_config_id.setter
    def llm_config_id(self, llm_config_id):
        """Sets the llm_config_id of this DataContextObject.


        :param llm_config_id: The llm_config_id of this DataContextObject.  # noqa: E501
        :type: object
        """

        self._llm_config_id = llm_config_id

    @property
    def error_message(self):
        """Gets the error_message of this DataContextObject.  # noqa: E501


        :return: The error_message of this DataContextObject.  # noqa: E501
        :rtype: object
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message):
        """Sets the error_message of this DataContextObject.


        :param error_message: The error_message of this DataContextObject.  # noqa: E501
        :type: object
        """

        self._error_message = error_message

    @property
    def config_ids(self):
        """Gets the config_ids of this DataContextObject.  # noqa: E501


        :return: The config_ids of this DataContextObject.  # noqa: E501
        :rtype: object
        """
        return self._config_ids

    @config_ids.setter
    def config_ids(self, config_ids):
        """Sets the config_ids of this DataContextObject.


        :param config_ids: The config_ids of this DataContextObject.  # noqa: E501
        :type: object
        """

        self._config_ids = config_ids

    @property
    def conn_schemas(self):
        """Gets the conn_schemas of this DataContextObject.  # noqa: E501


        :return: The conn_schemas of this DataContextObject.  # noqa: E501
        :rtype: object
        """
        return self._conn_schemas

    @conn_schemas.setter
    def conn_schemas(self, conn_schemas):
        """Sets the conn_schemas of this DataContextObject.


        :param conn_schemas: The conn_schemas of this DataContextObject.  # noqa: E501
        :type: object
        """

        self._conn_schemas = conn_schemas

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DataContextObject, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DataContextObject):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
