# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DataContextResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'object',
        'name': 'object',
        'ready': 'object',
        'conn_schema': 'object',
        'error_message': 'object',
        'config': 'object'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'ready': 'ready',
        'conn_schema': 'conn_schema',
        'error_message': 'error_message',
        'config': 'config'
    }

    def __init__(self, id=None, name=None, ready=None, conn_schema=None, error_message=None, config=None):  # noqa: E501
        """DataContextResponse - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._ready = None
        self._conn_schema = None
        self._error_message = None
        self._config = None
        self.discriminator = None
        self.id = id
        self.name = name
        self.ready = ready
        self.conn_schema = conn_schema
        if error_message is not None:
            self.error_message = error_message
        if config is not None:
            self.config = config

    @property
    def id(self):
        """Gets the id of this DataContextResponse.  # noqa: E501


        :return: The id of this DataContextResponse.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this DataContextResponse.


        :param id: The id of this DataContextResponse.  # noqa: E501
        :type: object
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this DataContextResponse.  # noqa: E501


        :return: The name of this DataContextResponse.  # noqa: E501
        :rtype: object
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this DataContextResponse.


        :param name: The name of this DataContextResponse.  # noqa: E501
        :type: object
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def ready(self):
        """Gets the ready of this DataContextResponse.  # noqa: E501


        :return: The ready of this DataContextResponse.  # noqa: E501
        :rtype: object
        """
        return self._ready

    @ready.setter
    def ready(self, ready):
        """Sets the ready of this DataContextResponse.


        :param ready: The ready of this DataContextResponse.  # noqa: E501
        :type: object
        """
        if ready is None:
            raise ValueError("Invalid value for `ready`, must not be `None`")  # noqa: E501

        self._ready = ready

    @property
    def conn_schema(self):
        """Gets the conn_schema of this DataContextResponse.  # noqa: E501


        :return: The conn_schema of this DataContextResponse.  # noqa: E501
        :rtype: object
        """
        return self._conn_schema

    @conn_schema.setter
    def conn_schema(self, conn_schema):
        """Sets the conn_schema of this DataContextResponse.


        :param conn_schema: The conn_schema of this DataContextResponse.  # noqa: E501
        :type: object
        """
        if conn_schema is None:
            raise ValueError("Invalid value for `conn_schema`, must not be `None`")  # noqa: E501

        self._conn_schema = conn_schema

    @property
    def error_message(self):
        """Gets the error_message of this DataContextResponse.  # noqa: E501


        :return: The error_message of this DataContextResponse.  # noqa: E501
        :rtype: object
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message):
        """Sets the error_message of this DataContextResponse.


        :param error_message: The error_message of this DataContextResponse.  # noqa: E501
        :type: object
        """

        self._error_message = error_message

    @property
    def config(self):
        """Gets the config of this DataContextResponse.  # noqa: E501


        :return: The config of this DataContextResponse.  # noqa: E501
        :rtype: object
        """
        return self._config

    @config.setter
    def config(self, config):
        """Sets the config of this DataContextResponse.


        :param config: The config of this DataContextResponse.  # noqa: E501
        :type: object
        """

        self._config = config

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DataContextResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DataContextResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
