# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GDriveExchangeRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'code': 'object',
        'redirect_uri': 'object',
        'connection_config_id': 'object'
    }

    attribute_map = {
        'code': 'code',
        'redirect_uri': 'redirect_uri',
        'connection_config_id': 'connection_config_id'
    }

    def __init__(self, code=None, redirect_uri=None, connection_config_id=None, *args, **kwargs):  # noqa: E501
        """GDriveExchangeRequest - a model defined in Swagger"""  # noqa: E501
        self._code = None
        self._redirect_uri = None
        self._connection_config_id = None
        self.discriminator = None
        self.code = code
        self.redirect_uri = redirect_uri
        self.connection_config_id = connection_config_id

    @property
    def code(self):
        """Gets the code of this GDriveExchangeRequest.  # noqa: E501


        :return: The code of this GDriveExchangeRequest.  # noqa: E501
        :rtype: object
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this GDriveExchangeRequest.


        :param code: The code of this GDriveExchangeRequest.  # noqa: E501
        :type: object
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def redirect_uri(self):
        """Gets the redirect_uri of this GDriveExchangeRequest.  # noqa: E501


        :return: The redirect_uri of this GDriveExchangeRequest.  # noqa: E501
        :rtype: object
        """
        return self._redirect_uri

    @redirect_uri.setter
    def redirect_uri(self, redirect_uri):
        """Sets the redirect_uri of this GDriveExchangeRequest.


        :param redirect_uri: The redirect_uri of this GDriveExchangeRequest.  # noqa: E501
        :type: object
        """
        if redirect_uri is None:
            raise ValueError("Invalid value for `redirect_uri`, must not be `None`")  # noqa: E501

        self._redirect_uri = redirect_uri

    @property
    def connection_config_id(self):
        """Gets the connection_config_id of this GDriveExchangeRequest.  # noqa: E501


        :return: The connection_config_id of this GDriveExchangeRequest.  # noqa: E501
        :rtype: object
        """
        return self._connection_config_id

    @connection_config_id.setter
    def connection_config_id(self, connection_config_id):
        """Sets the connection_config_id of this GDriveExchangeRequest.


        :param connection_config_id: The connection_config_id of this GDriveExchangeRequest.  # noqa: E501
        :type: object
        """
        if connection_config_id is None:
            raise ValueError("Invalid value for `connection_config_id`, must not be `None`")  # noqa: E501

        self._connection_config_id = connection_config_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GDriveExchangeRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GDriveExchangeRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
