# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LimitObject(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'has_limit': 'object',
        'limit': 'object',
        'start_time': 'object',
        'end_time': 'object',
        'remaining': 'object'
    }

    attribute_map = {
        'has_limit': 'has_limit',
        'limit': 'limit',
        'start_time': 'start_time',
        'end_time': 'end_time',
        'remaining': 'remaining'
    }

    def __init__(self, has_limit=None, limit=None, start_time=None, end_time=None, remaining=None):  # noqa: E501
        """LimitObject - a model defined in Swagger"""  # noqa: E501
        self._has_limit = None
        self._limit = None
        self._start_time = None
        self._end_time = None
        self._remaining = None
        self.discriminator = None
        self.has_limit = has_limit
        if limit is not None:
            self.limit = limit
        if start_time is not None:
            self.start_time = start_time
        if end_time is not None:
            self.end_time = end_time
        if remaining is not None:
            self.remaining = remaining

    @property
    def has_limit(self):
        """Gets the has_limit of this LimitObject.  # noqa: E501


        :return: The has_limit of this LimitObject.  # noqa: E501
        :rtype: object
        """
        return self._has_limit

    @has_limit.setter
    def has_limit(self, has_limit):
        """Sets the has_limit of this LimitObject.


        :param has_limit: The has_limit of this LimitObject.  # noqa: E501
        :type: object
        """
        if has_limit is None:
            raise ValueError("Invalid value for `has_limit`, must not be `None`")  # noqa: E501

        self._has_limit = has_limit

    @property
    def limit(self):
        """Gets the limit of this LimitObject.  # noqa: E501


        :return: The limit of this LimitObject.  # noqa: E501
        :rtype: object
        """
        return self._limit

    @limit.setter
    def limit(self, limit):
        """Sets the limit of this LimitObject.


        :param limit: The limit of this LimitObject.  # noqa: E501
        :type: object
        """

        self._limit = limit

    @property
    def start_time(self):
        """Gets the start_time of this LimitObject.  # noqa: E501


        :return: The start_time of this LimitObject.  # noqa: E501
        :rtype: object
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        """Sets the start_time of this LimitObject.


        :param start_time: The start_time of this LimitObject.  # noqa: E501
        :type: object
        """

        self._start_time = start_time

    @property
    def end_time(self):
        """Gets the end_time of this LimitObject.  # noqa: E501


        :return: The end_time of this LimitObject.  # noqa: E501
        :rtype: object
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time):
        """Sets the end_time of this LimitObject.


        :param end_time: The end_time of this LimitObject.  # noqa: E501
        :type: object
        """

        self._end_time = end_time

    @property
    def remaining(self):
        """Gets the remaining of this LimitObject.  # noqa: E501


        :return: The remaining of this LimitObject.  # noqa: E501
        :rtype: object
        """
        return self._remaining

    @remaining.setter
    def remaining(self, remaining):
        """Sets the remaining of this LimitObject.


        :param remaining: The remaining of this LimitObject.  # noqa: E501
        :type: object
        """

        self._remaining = remaining

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LimitObject, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LimitObject):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
