# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ModelConfigObject(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'object',
        'name': 'object',
        'url': 'object',
        'token': 'object',
        'model_name': 'object',
        'on_prem': 'object'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'url': 'url',
        'token': 'token',
        'model_name': 'model_name',
        'on_prem': 'on_prem'
    }

    def __init__(self, id=None, name=None, url=None, token=None, model_name=None, on_prem=None):  # noqa: E501
        """ModelConfigObject - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._url = None
        self._token = None
        self._model_name = None
        self._on_prem = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if url is not None:
            self.url = url
        if token is not None:
            self.token = token
        if model_name is not None:
            self.model_name = model_name
        if on_prem is not None:
            self.on_prem = on_prem

    @property
    def id(self):
        """Gets the id of this ModelConfigObject.  # noqa: E501


        :return: The id of this ModelConfigObject.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ModelConfigObject.


        :param id: The id of this ModelConfigObject.  # noqa: E501
        :type: object
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this ModelConfigObject.  # noqa: E501


        :return: The name of this ModelConfigObject.  # noqa: E501
        :rtype: object
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ModelConfigObject.


        :param name: The name of this ModelConfigObject.  # noqa: E501
        :type: object
        """

        self._name = name

    @property
    def url(self):
        """Gets the url of this ModelConfigObject.  # noqa: E501


        :return: The url of this ModelConfigObject.  # noqa: E501
        :rtype: object
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this ModelConfigObject.


        :param url: The url of this ModelConfigObject.  # noqa: E501
        :type: object
        """

        self._url = url

    @property
    def token(self):
        """Gets the token of this ModelConfigObject.  # noqa: E501


        :return: The token of this ModelConfigObject.  # noqa: E501
        :rtype: object
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this ModelConfigObject.


        :param token: The token of this ModelConfigObject.  # noqa: E501
        :type: object
        """

        self._token = token

    @property
    def model_name(self):
        """Gets the model_name of this ModelConfigObject.  # noqa: E501


        :return: The model_name of this ModelConfigObject.  # noqa: E501
        :rtype: object
        """
        return self._model_name

    @model_name.setter
    def model_name(self, model_name):
        """Sets the model_name of this ModelConfigObject.


        :param model_name: The model_name of this ModelConfigObject.  # noqa: E501
        :type: object
        """

        self._model_name = model_name

    @property
    def on_prem(self):
        """Gets the on_prem of this ModelConfigObject.  # noqa: E501


        :return: The on_prem of this ModelConfigObject.  # noqa: E501
        :rtype: object
        """
        return self._on_prem

    @on_prem.setter
    def on_prem(self, on_prem):
        """Sets the on_prem of this ModelConfigObject.


        :param on_prem: The on_prem of this ModelConfigObject.  # noqa: E501
        :type: object
        """

        self._on_prem = on_prem

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ModelConfigObject, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ModelConfigObject):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
