# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class NodeObject(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'object',
        'name': 'object',
        'description': 'object',
        'change_hash': 'object',
        'change_list': 'object',
        'fill': 'object'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'description': 'description',
        'change_hash': 'change_hash',
        'change_list': 'change_list',
        'fill': 'fill'
    }

    def __init__(self, id=None, name=None, description=None, change_hash=None, change_list=None, fill=None, *args, **kwargs):  # noqa: E501
        """NodeObject - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._description = None
        self._change_hash = None
        self._change_list = None
        self._fill = None
        self.discriminator = None
        self.id = id
        self.name = name
        if description is not None:
            self.description = description
        if change_hash is not None:
            self.change_hash = change_hash
        if change_list is not None:
            self.change_list = change_list
        if fill is not None:
            self.fill = fill

    @property
    def id(self):
        """Gets the id of this NodeObject.  # noqa: E501


        :return: The id of this NodeObject.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this NodeObject.


        :param id: The id of this NodeObject.  # noqa: E501
        :type: object
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this NodeObject.  # noqa: E501


        :return: The name of this NodeObject.  # noqa: E501
        :rtype: object
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this NodeObject.


        :param name: The name of this NodeObject.  # noqa: E501
        :type: object
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self):
        """Gets the description of this NodeObject.  # noqa: E501


        :return: The description of this NodeObject.  # noqa: E501
        :rtype: object
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this NodeObject.


        :param description: The description of this NodeObject.  # noqa: E501
        :type: object
        """

        self._description = description

    @property
    def change_hash(self):
        """Gets the change_hash of this NodeObject.  # noqa: E501


        :return: The change_hash of this NodeObject.  # noqa: E501
        :rtype: object
        """
        return self._change_hash

    @change_hash.setter
    def change_hash(self, change_hash):
        """Sets the change_hash of this NodeObject.


        :param change_hash: The change_hash of this NodeObject.  # noqa: E501
        :type: object
        """

        self._change_hash = change_hash

    @property
    def change_list(self):
        """Gets the change_list of this NodeObject.  # noqa: E501


        :return: The change_list of this NodeObject.  # noqa: E501
        :rtype: object
        """
        return self._change_list

    @change_list.setter
    def change_list(self, change_list):
        """Sets the change_list of this NodeObject.


        :param change_list: The change_list of this NodeObject.  # noqa: E501
        :type: object
        """

        self._change_list = change_list

    @property
    def fill(self):
        """Gets the fill of this NodeObject.  # noqa: E501


        :return: The fill of this NodeObject.  # noqa: E501
        :rtype: object
        """
        return self._fill

    @fill.setter
    def fill(self, fill):
        """Sets the fill of this NodeObject.


        :param fill: The fill of this NodeObject.  # noqa: E501
        :type: object
        """

        self._fill = fill

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NodeObject, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NodeObject):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
