# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class QuestionObject(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'index': 'object',
        'question': 'object',
        'answer': 'object',
        'id': 'object',
        'evaluation_id': 'object'
    }

    attribute_map = {
        'index': 'index',
        'question': 'question',
        'answer': 'answer',
        'id': 'id',
        'evaluation_id': 'evaluation_id'
    }

    def __init__(self, index=None, question=None, answer=None, id=None, evaluation_id=None):  # noqa: E501
        """QuestionObject - a model defined in Swagger"""  # noqa: E501
        self._index = None
        self._question = None
        self._answer = None
        self._id = None
        self._evaluation_id = None
        self.discriminator = None
        self.index = index
        self.question = question
        self.answer = answer
        if id is not None:
            self.id = id
        if evaluation_id is not None:
            self.evaluation_id = evaluation_id

    @property
    def index(self):
        """Gets the index of this QuestionObject.  # noqa: E501


        :return: The index of this QuestionObject.  # noqa: E501
        :rtype: object
        """
        return self._index

    @index.setter
    def index(self, index):
        """Sets the index of this QuestionObject.


        :param index: The index of this QuestionObject.  # noqa: E501
        :type: object
        """
        if index is None:
            raise ValueError("Invalid value for `index`, must not be `None`")  # noqa: E501

        self._index = index

    @property
    def question(self):
        """Gets the question of this QuestionObject.  # noqa: E501


        :return: The question of this QuestionObject.  # noqa: E501
        :rtype: object
        """
        return self._question

    @question.setter
    def question(self, question):
        """Sets the question of this QuestionObject.


        :param question: The question of this QuestionObject.  # noqa: E501
        :type: object
        """
        if question is None:
            raise ValueError("Invalid value for `question`, must not be `None`")  # noqa: E501

        self._question = question

    @property
    def answer(self):
        """Gets the answer of this QuestionObject.  # noqa: E501


        :return: The answer of this QuestionObject.  # noqa: E501
        :rtype: object
        """
        return self._answer

    @answer.setter
    def answer(self, answer):
        """Sets the answer of this QuestionObject.


        :param answer: The answer of this QuestionObject.  # noqa: E501
        :type: object
        """
        if answer is None:
            raise ValueError("Invalid value for `answer`, must not be `None`")  # noqa: E501

        self._answer = answer

    @property
    def id(self):
        """Gets the id of this QuestionObject.  # noqa: E501


        :return: The id of this QuestionObject.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this QuestionObject.


        :param id: The id of this QuestionObject.  # noqa: E501
        :type: object
        """

        self._id = id

    @property
    def evaluation_id(self):
        """Gets the evaluation_id of this QuestionObject.  # noqa: E501


        :return: The evaluation_id of this QuestionObject.  # noqa: E501
        :rtype: object
        """
        return self._evaluation_id

    @evaluation_id.setter
    def evaluation_id(self, evaluation_id):
        """Sets the evaluation_id of this QuestionObject.


        :param evaluation_id: The evaluation_id of this QuestionObject.  # noqa: E501
        :type: object
        """

        self._evaluation_id = evaluation_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(QuestionObject, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, QuestionObject):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
