# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RemoteFilesResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'new': 'object',
        'removed': 'object',
        'unchanged': 'object'
    }

    attribute_map = {
        'new': 'new',
        'removed': 'removed',
        'unchanged': 'unchanged'
    }

    def __init__(self, new=None, removed=None, unchanged=None, *args, **kwargs):  # noqa: E501
        """RemoteFilesResponse - a model defined in Swagger"""  # noqa: E501
        self._new = None
        self._removed = None
        self._unchanged = None
        self.discriminator = None
        self.new = new
        self.removed = removed
        self.unchanged = unchanged

    @property
    def new(self):
        """Gets the new of this RemoteFilesResponse.  # noqa: E501


        :return: The new of this RemoteFilesResponse.  # noqa: E501
        :rtype: object
        """
        return self._new

    @new.setter
    def new(self, new):
        """Sets the new of this RemoteFilesResponse.


        :param new: The new of this RemoteFilesResponse.  # noqa: E501
        :type: object
        """
        if new is None:
            raise ValueError("Invalid value for `new`, must not be `None`")  # noqa: E501

        self._new = new

    @property
    def removed(self):
        """Gets the removed of this RemoteFilesResponse.  # noqa: E501


        :return: The removed of this RemoteFilesResponse.  # noqa: E501
        :rtype: object
        """
        return self._removed

    @removed.setter
    def removed(self, removed):
        """Sets the removed of this RemoteFilesResponse.


        :param removed: The removed of this RemoteFilesResponse.  # noqa: E501
        :type: object
        """
        if removed is None:
            raise ValueError("Invalid value for `removed`, must not be `None`")  # noqa: E501

        self._removed = removed

    @property
    def unchanged(self):
        """Gets the unchanged of this RemoteFilesResponse.  # noqa: E501


        :return: The unchanged of this RemoteFilesResponse.  # noqa: E501
        :rtype: object
        """
        return self._unchanged

    @unchanged.setter
    def unchanged(self, unchanged):
        """Sets the unchanged of this RemoteFilesResponse.


        :param unchanged: The unchanged of this RemoteFilesResponse.  # noqa: E501
        :type: object
        """
        if unchanged is None:
            raise ValueError("Invalid value for `unchanged`, must not be `None`")  # noqa: E501

        self._unchanged = unchanged

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RemoteFilesResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RemoteFilesResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
