# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ResponseTimeSample(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        '_date': 'object',
        'mean_response_time': 'object'
    }

    attribute_map = {
        '_date': 'date',
        'mean_response_time': 'mean_response_time'
    }

    def __init__(self, _date=None, mean_response_time=None):  # noqa: E501
        """ResponseTimeSample - a model defined in Swagger"""  # noqa: E501
        self.__date = None
        self._mean_response_time = None
        self.discriminator = None
        self._date = _date
        self.mean_response_time = mean_response_time

    @property
    def _date(self):
        """Gets the _date of this ResponseTimeSample.  # noqa: E501


        :return: The _date of this ResponseTimeSample.  # noqa: E501
        :rtype: object
        """
        return self.__date

    @_date.setter
    def _date(self, _date):
        """Sets the _date of this ResponseTimeSample.


        :param _date: The _date of this ResponseTimeSample.  # noqa: E501
        :type: object
        """
        if _date is None:
            raise ValueError("Invalid value for `_date`, must not be `None`")  # noqa: E501

        self.__date = _date

    @property
    def mean_response_time(self):
        """Gets the mean_response_time of this ResponseTimeSample.  # noqa: E501


        :return: The mean_response_time of this ResponseTimeSample.  # noqa: E501
        :rtype: object
        """
        return self._mean_response_time

    @mean_response_time.setter
    def mean_response_time(self, mean_response_time):
        """Sets the mean_response_time of this ResponseTimeSample.


        :param mean_response_time: The mean_response_time of this ResponseTimeSample.  # noqa: E501
        :type: object
        """
        if mean_response_time is None:
            raise ValueError("Invalid value for `mean_response_time`, must not be `None`")  # noqa: E501

        self._mean_response_time = mean_response_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ResponseTimeSample, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ResponseTimeSample):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
