# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TokensSample(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        '_date': 'object',
        'cached': 'object',
        'input': 'object',
        'output': 'object',
        'response': 'object',
        'total': 'object'
    }

    attribute_map = {
        '_date': 'date',
        'cached': 'cached',
        'input': 'input',
        'output': 'output',
        'response': 'response',
        'total': 'total'
    }

    def __init__(self, _date=None, cached=None, input=None, output=None, response=None, total=None):  # noqa: E501
        """TokensSample - a model defined in Swagger"""  # noqa: E501
        self.__date = None
        self._cached = None
        self._input = None
        self._output = None
        self._response = None
        self._total = None
        self.discriminator = None
        self._date = _date
        self.cached = cached
        self.input = input
        self.output = output
        self.response = response
        self.total = total

    @property
    def _date(self):
        """Gets the _date of this TokensSample.  # noqa: E501


        :return: The _date of this TokensSample.  # noqa: E501
        :rtype: object
        """
        return self.__date

    @_date.setter
    def _date(self, _date):
        """Sets the _date of this TokensSample.


        :param _date: The _date of this TokensSample.  # noqa: E501
        :type: object
        """
        if _date is None:
            raise ValueError("Invalid value for `_date`, must not be `None`")  # noqa: E501

        self.__date = _date

    @property
    def cached(self):
        """Gets the cached of this TokensSample.  # noqa: E501


        :return: The cached of this TokensSample.  # noqa: E501
        :rtype: object
        """
        return self._cached

    @cached.setter
    def cached(self, cached):
        """Sets the cached of this TokensSample.


        :param cached: The cached of this TokensSample.  # noqa: E501
        :type: object
        """
        if cached is None:
            raise ValueError("Invalid value for `cached`, must not be `None`")  # noqa: E501

        self._cached = cached

    @property
    def input(self):
        """Gets the input of this TokensSample.  # noqa: E501


        :return: The input of this TokensSample.  # noqa: E501
        :rtype: object
        """
        return self._input

    @input.setter
    def input(self, input):
        """Sets the input of this TokensSample.


        :param input: The input of this TokensSample.  # noqa: E501
        :type: object
        """
        if input is None:
            raise ValueError("Invalid value for `input`, must not be `None`")  # noqa: E501

        self._input = input

    @property
    def output(self):
        """Gets the output of this TokensSample.  # noqa: E501


        :return: The output of this TokensSample.  # noqa: E501
        :rtype: object
        """
        return self._output

    @output.setter
    def output(self, output):
        """Sets the output of this TokensSample.


        :param output: The output of this TokensSample.  # noqa: E501
        :type: object
        """
        if output is None:
            raise ValueError("Invalid value for `output`, must not be `None`")  # noqa: E501

        self._output = output

    @property
    def response(self):
        """Gets the response of this TokensSample.  # noqa: E501


        :return: The response of this TokensSample.  # noqa: E501
        :rtype: object
        """
        return self._response

    @response.setter
    def response(self, response):
        """Sets the response of this TokensSample.


        :param response: The response of this TokensSample.  # noqa: E501
        :type: object
        """
        if response is None:
            raise ValueError("Invalid value for `response`, must not be `None`")  # noqa: E501

        self._response = response

    @property
    def total(self):
        """Gets the total of this TokensSample.  # noqa: E501


        :return: The total of this TokensSample.  # noqa: E501
        :rtype: object
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this TokensSample.


        :param total: The total of this TokensSample.  # noqa: E501
        :type: object
        """
        if total is None:
            raise ValueError("Invalid value for `total`, must not be `None`")  # noqa: E501

        self._total = total

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TokensSample, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TokensSample):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
