# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UserPublic(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'email': 'object',
        'first_name': 'object',
        'last_name': 'object',
        'profile_image_url': 'object',
        'id': 'object',
        'permission_group': 'object'
    }

    attribute_map = {
        'email': 'email',
        'first_name': 'first_name',
        'last_name': 'last_name',
        'profile_image_url': 'profile_image_url',
        'id': 'id',
        'permission_group': 'permission_group'
    }

    def __init__(self, email=None, first_name=None, last_name=None, profile_image_url=None, id=None, permission_group=None):  # noqa: E501
        """UserPublic - a model defined in Swagger"""  # noqa: E501
        self._email = None
        self._first_name = None
        self._last_name = None
        self._profile_image_url = None
        self._id = None
        self._permission_group = None
        self.discriminator = None
        self.email = email
        self.first_name = first_name
        self.last_name = last_name
        if profile_image_url is not None:
            self.profile_image_url = profile_image_url
        if id is not None:
            self.id = id
        if permission_group is not None:
            self.permission_group = permission_group

    @property
    def email(self):
        """Gets the email of this UserPublic.  # noqa: E501


        :return: The email of this UserPublic.  # noqa: E501
        :rtype: object
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this UserPublic.


        :param email: The email of this UserPublic.  # noqa: E501
        :type: object
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def first_name(self):
        """Gets the first_name of this UserPublic.  # noqa: E501


        :return: The first_name of this UserPublic.  # noqa: E501
        :rtype: object
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this UserPublic.


        :param first_name: The first_name of this UserPublic.  # noqa: E501
        :type: object
        """
        if first_name is None:
            raise ValueError("Invalid value for `first_name`, must not be `None`")  # noqa: E501

        self._first_name = first_name

    @property
    def last_name(self):
        """Gets the last_name of this UserPublic.  # noqa: E501


        :return: The last_name of this UserPublic.  # noqa: E501
        :rtype: object
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this UserPublic.


        :param last_name: The last_name of this UserPublic.  # noqa: E501
        :type: object
        """
        if last_name is None:
            raise ValueError("Invalid value for `last_name`, must not be `None`")  # noqa: E501

        self._last_name = last_name

    @property
    def profile_image_url(self):
        """Gets the profile_image_url of this UserPublic.  # noqa: E501


        :return: The profile_image_url of this UserPublic.  # noqa: E501
        :rtype: object
        """
        return self._profile_image_url

    @profile_image_url.setter
    def profile_image_url(self, profile_image_url):
        """Sets the profile_image_url of this UserPublic.


        :param profile_image_url: The profile_image_url of this UserPublic.  # noqa: E501
        :type: object
        """

        self._profile_image_url = profile_image_url

    @property
    def id(self):
        """Gets the id of this UserPublic.  # noqa: E501


        :return: The id of this UserPublic.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this UserPublic.


        :param id: The id of this UserPublic.  # noqa: E501
        :type: object
        """

        self._id = id

    @property
    def permission_group(self):
        """Gets the permission_group of this UserPublic.  # noqa: E501


        :return: The permission_group of this UserPublic.  # noqa: E501
        :rtype: object
        """
        return self._permission_group

    @permission_group.setter
    def permission_group(self, permission_group):
        """Sets the permission_group of this UserPublic.


        :param permission_group: The permission_group of this UserPublic.  # noqa: E501
        :type: object
        """

        self._permission_group = permission_group

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserPublic, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserPublic):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
