# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UserAPIKeys(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'primary_key': 'APIKey',
        'replacement_key': 'object'
    }

    attribute_map = {
        'primary_key': 'primary_key',
        'replacement_key': 'replacement_key'
    }

    def __init__(self, primary_key=None, replacement_key=None):  # noqa: E501
        """UserAPIKeys - a model defined in Swagger"""  # noqa: E501
        self._primary_key = None
        self._replacement_key = None
        self.discriminator = None
        self.primary_key = primary_key
        if replacement_key is not None:
            self.replacement_key = replacement_key

    @property
    def primary_key(self):
        """Gets the primary_key of this UserAPIKeys.  # noqa: E501


        :return: The primary_key of this UserAPIKeys.  # noqa: E501
        :rtype: APIKey
        """
        return self._primary_key

    @primary_key.setter
    def primary_key(self, primary_key):
        """Sets the primary_key of this UserAPIKeys.


        :param primary_key: The primary_key of this UserAPIKeys.  # noqa: E501
        :type: APIKey
        """
        if primary_key is None:
            raise ValueError("Invalid value for `primary_key`, must not be `None`")  # noqa: E501

        self._primary_key = primary_key

    @property
    def replacement_key(self):
        """Gets the replacement_key of this UserAPIKeys.  # noqa: E501


        :return: The replacement_key of this UserAPIKeys.  # noqa: E501
        :rtype: object
        """
        return self._replacement_key

    @replacement_key.setter
    def replacement_key(self, replacement_key):
        """Sets the replacement_key of this UserAPIKeys.


        :param replacement_key: The replacement_key of this UserAPIKeys.  # noqa: E501
        :type: object
        """

        self._replacement_key = replacement_key

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserAPIKeys, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserAPIKeys):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
